Repository MovingBlocks/Terasology, pull requests merged in 2018-10, with the labels that each got.

#3473 Fix liquid rendering
  engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
  engine/src/main/java/org/terasology/world/block/Block.java
  engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java
  engine/src/main/resources/assets/shapes/trimmedLoweredCube.shape
  engine/src/main/resources/assets/shapes/trimmedRaisedCube.shape
  modules/Core/assets/blocks/liquid/Lava.block
  modules/Core/assets/blocks/liquid/Water.block
Labels: Bug, Rendering

#3498 hotfix that fixes the rotation issue with structured templates
  engine/src/main/java/org/terasology/world/block/family/FreeformFamily.java
  engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java
Labels: Bug

#3502 Checkboxes are now generated dynamically
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/CheckboxAssociationEnum.java
Labels: UI

#3526 RecordAndReplayCurrentStatus' javadoc update to reflect the UI changes made on #3506
  engine/src/main/java/org/terasology/recording/RecordAndReplayCurrentStatus.java
Labels: Documentation
