Repository MovingBlocks/Terasology, pull requests merged in 2018-04, with the labels that each got.

#3269 Bug Character can jump once under water fixed
  engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
Labels: Bug

#3276 RenderGraph Enhancements
  engine-tests/src/test/java/org/terasology/rendering/dag/RenderTaskListGeneratorTest.java
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java
  engine/src/main/java/org/terasology/engine/subsystem/headless/renderer/HeadlessWorldRenderer.java
  engine/src/main/java/org/terasology/rendering/dag/AbstractNode.java
  engine/src/main/java/org/terasology/rendering/dag/ConditionDependentNode.java
  engine/src/main/java/org/terasology/rendering/dag/Node.java
  engine/src/main/java/org/terasology/rendering/dag/RenderGraph.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/AlphaRejectBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/AmbientOcclusionNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/ApplyDeferredLightingNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/BackdropReflectionNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/BloomBlurNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/BlurNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/BlurredAmbientOcclusionNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/BufferClearingNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/DeferredMainLightNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/DeferredPointLightsNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/DownSamplerForExposureNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/DownSamplerNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/FinalPostProcessingNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/HazeNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/HighPassNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/InitialPostProcessingNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/LateBlurNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/LightShaftsNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueObjectsNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OutlineNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OutputToHMDNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OutputToScreenNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OverlaysNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/PrePostCompositeNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/RefractiveReflectiveBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/SimpleBlendMaterialsNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/ToneMappingNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/UpdateExposureNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/package-info.java
  engine/src/main/java/org/terasology/rendering/dag/package-info.java
  engine/src/main/java/org/terasology/rendering/dag/stateChanges/package-info.java
  engine/src/main/java/org/terasology/rendering/opengl/fbms/package-info.java
  engine/src/main/java/org/terasology/rendering/opengl/package-info.java
  engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
  engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
Labels: Architecture, Rendering

#3303 Fixes #3139-Pause on menu
  engine/src/main/java/org/terasology/logic/players/MenuControlSystem.java
Labels: UI

#3212 Polish menu i18n update - added all missing entries
  engine/src/main/resources/assets/i18n/menu_pl.lang
Labels: UI

#3328 Fixed : Time remains paused even when the back button is clicked in the pause menu.
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java
Labels: Bug, UI

#3308 Fix parallax and normal mapping
  engine/src/main/java/org/terasology/rendering/dag/nodes/AlphaRejectBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/RefractiveReflectiveBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
  engine/src/main/java/org/terasology/world/block/tiles/WorldAtlasImpl.java
  engine/src/main/resources/assets/shaders/chunk_frag.glsl
Labels: Rendering

#3339 Added links to discord and to intellij download in readme
  README.markdown
Labels: Doc

#3301 Add confirmation popup for button Delete on SelectGame screen
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/TwoButtonPopup.java
  engine/src/main/resources/assets/i18n/menu.lang
  engine/src/main/resources/assets/i18n/menu_en.lang
  engine/src/main/resources/assets/i18n/menu_ru.lang
  engine/src/main/resources/assets/ui/menu/twoButtonPopup.ui
Labels: UI

#3335 Show error if module loading fails.
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WaitPopup.java
Labels: UI
