Repository MovingBlocks/Terasology, pull requests merged in 2018-03, with the labels that each got.

#3277 Fix scrolling when there's already enough space.
  engine/src/main/java/org/terasology/rendering/nui/widgets/UIScrollbar.java
Labels: UI

#3286 Fix javaDoc (try #2)
  engine/src/main/java/org/terasology/logic/console/Console.java
Labels: Doc

#3291 Added back face culling to several nodes
  engine/src/main/java/org/terasology/rendering/dag/nodes/AlphaRejectBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueObjectsNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OverlaysNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
  engine/src/main/java/org/terasology/rendering/primitives/ChunkMesh.java
Labels: Rendering

#3289 Fix #2246 Volumetric Fog broken
  engine/src/main/java/org/terasology/rendering/dag/nodes/PrePostCompositeNode.java
  engine/src/main/resources/assets/shaders/prePostComposite_frag.glsl
  engine/src/main/resources/assets/ui/menu/videoMenuScreen.ui
  engine/src/main/resources/org/terasology/include/globalFunctionsFragIncl.glsl
Labels: Rendering

#3284 'groovyw * list' output condensed format
  config/groovy/util.groovy
Labels: Logistics
