Repository MovingBlocks/Terasology, pull requests merged in 2018-05, with the labels that each got.

#3319 Added Javadocs to a number of Renderer-related packages, classes and methods.
  engine/src/main/java/org/terasology/rendering/dag/AbstractNode.java
  engine/src/main/java/org/terasology/rendering/dag/Node.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/package-info.java
  engine/src/main/java/org/terasology/rendering/dag/package-info.java
  engine/src/main/java/org/terasology/rendering/dag/stateChanges/package-info.java
  engine/src/main/java/org/terasology/rendering/opengl/AbstractFBOsManager.java
  engine/src/main/java/org/terasology/rendering/opengl/BaseFBOsManager.java
  engine/src/main/java/org/terasology/rendering/opengl/fbms/DisplayResolutionDependentFBOs.java
  engine/src/main/java/org/terasology/rendering/opengl/fbms/ImmutableFBOs.java
  engine/src/main/java/org/terasology/rendering/opengl/fbms/ShadowMapResolutionDependentFBOs.java
  engine/src/main/java/org/terasology/rendering/opengl/fbms/package-info.java
  engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
Labels: API, Architecture, Doc, Rendering

#3332 Add Server Blacklist and Whitelist
  engine-tests/src/test/java/org/terasology/network/internal/NetworkOwnershipTest.java
  engine/src/main/java/org/terasology/engine/subsystem/common/NetworkSubsystem.java
  engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java
  engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
  engine/src/main/java/org/terasology/network/internal/ServerConnectListManager.java
  engine/src/main/java/org/terasology/protobuf/NetData.java
  engine/src/main/protobuf/NetMessage.proto
Labels: Logistics, Multiplayer, Security

#3371 PathManager fix - better identify working directory on launch
  engine/src/main/java/org/terasology/engine/paths/PathManager.java
Labels: Logistics

#3361 Update select game screen
  engine-tests/src/test/java/org/terasology/rendering/assets/texture/AWTTextureFormatTest.java
  engine-tests/src/test/java/org/terasology/rendering/nui/layers/mainMenu/GameProviderTest.java
  engine-tests/src/test/resources/gameManifest.json
  engine/src/main/java/org/terasology/engine/TerasologyConstants.java
  engine/src/main/java/org/terasology/engine/modes/StateIngame.java
  engine/src/main/java/org/terasology/rendering/assets/texture/AWTTextureFormat.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameInfo.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProvider.java
  engine/src/main/java/org/terasology/rendering/opengl/ScreenGrabber.java
  engine/src/main/resources/assets/i18n/menu_en.lang
  engine/src/main/resources/assets/i18n/menu_ru.lang
  engine/src/main/resources/assets/textures/defaultPreview.jpeg
  engine/src/main/resources/assets/ui/menu/selectGameScreen.ui
Labels: UI

#3369 Add method to set entity at location
  engine/src/main/java/org/terasology/world/BlockEntityRegistry.java
  engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
Labels: API, Feature, WORK IN PROGRESS
