Repository MovingBlocks/Terasology, pull requests merged in 2018-06, with the labels that each got.

#3311 Network code documentation
  engine/src/main/java/org/terasology/network/internal/AbstractClient.java
  engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java
  engine/src/main/java/org/terasology/network/internal/ClientHandshakeHandler.java
  engine/src/main/java/org/terasology/network/internal/JoinStatusImpl.java
  engine/src/main/java/org/terasology/network/internal/LocalClient.java
  engine/src/main/java/org/terasology/network/internal/NetClient.java
Labels: Doc, WORK IN PROGRESS

#3329 Fix to online players overlay not displayig all of the players
  engine/src/main/java/org/terasology/network/ServerPingSystem.java
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/OnlinePlayersOverlay.java
Labels: Multiplayer, UI

#3389 fixed rotation issue with freeform family and added more detailed logging information for BlockFamily
  engine/src/main/java/org/terasology/world/block/family/AbstractBlockFamily.java
  engine/src/main/java/org/terasology/world/block/family/FreeformFamily.java
Labels: Bug
