Repository MovingBlocks/Terasology, pull requests merged in 2018-09, with the labels that each got.

#3477 Add rendering enums as API
  engine/src/main/java/org/terasology/rendering/primitives/ChunkMesh.java
  engine/src/main/java/org/terasology/rendering/primitives/ChunkVertexFlag.java
Labels: Rendering, Security

#3479 Make water-waves actually vertical
  engine/src/main/resources/assets/shaders/chunk_vert.glsl
Labels: Rendering

#3494 Permissive security flags with fixed formatting. Fixes #3444
  engine/src/main/java/org/terasology/config/SystemConfig.java
  engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Logistics, Security, UI
