Repository MovingBlocks/Terasology, pull requests merged in 2018-11, with the labels that each got.

#3536 Overhauled R&R serialization
  engine-tests/src/test/java/org/terasology/persistence/internal/StorageManagerTest.java
  engine-tests/src/test/java/org/terasology/recording/EventSystemReplayImplTest.java
  engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/CharacterTypeHandler.java
  engine/src/main/java/org/terasology/recording/RecordAndReplaySerializer.java
  engine/src/main/java/org/terasology/recording/RecordedEventSerializer.java
Labels: Architecture

#3548 Add GUI screen to name a recording
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NameRecordingScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/RecordScreen.java
  engine/src/main/resources/assets/i18n/menu.lang
  engine/src/main/resources/assets/i18n/menu_en.lang
  engine/src/main/resources/assets/i18n/menu_fr.lang
  engine/src/main/resources/assets/ui/menu/nameRecordingScreen.ui
Labels: GCI, UI

#3552 Fixed LGTM Issue - Dereferenced variable may be null - GCI
  engine/src/main/java/org/terasology/rendering/collada/ColladaLoader.java
Labels: Bug

#3554 Player can't create a game with special name from the player
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
Labels: Bug, UI

#3541 Fix LGTM warnings "Result of multiplication cast to wider type" - GCI
  engine/src/main/java/org/terasology/engine/internal/TimeBase.java
  engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/math/MatrixUtils.java
  engine/src/main/java/org/terasology/persistence/internal/ReadWriteStorageManager.java
  engine/src/main/java/org/terasology/rendering/cameras/FrustumPlane.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/ShadowMapNode.java
  engine/src/main/java/org/terasology/rendering/nui/internal/Line.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/PlayerSettingsScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layouts/ColumnLayout.java
  engine/src/main/java/org/terasology/rendering/nui/layouts/MultiRowLayout.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/UIRadialRing.java
  engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
  engine/src/main/java/org/terasology/utilities/procedural/HeightmapFileReader.java
  engine/src/main/java/org/terasology/utilities/procedural/Voronoi.java
  engine/src/main/java/org/terasology/world/time/WorldTimeEvent.java
Labels: Architecture, Bug

#3555 Bringing people who know Terasology together in discord
  engine/build.gradle
  engine/src/main/java/org/terasology/config/PlayerConfig.java
  engine/src/main/java/org/terasology/engine/subsystem/rpc/DiscordRPCSubSystem.java
  engine/src/main/java/org/terasology/entitySystem/systems/DiscordRPCSystem.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/PlayerSettingsScreen.java
  engine/src/main/resources/assets/i18n/menu.lang
  engine/src/main/resources/assets/i18n/menu_ar.lang
  engine/src/main/resources/assets/i18n/menu_en.lang
  engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
  git
Labels: Logistics, UI
