Repository MovingBlocks/Terasology, pull requests merged in 2018-07, with the labels that each got.

#3404 Fix remotely held items @commands broken by #3379, brought by #3337
  engine/src/main/java/org/terasology/logic/players/ThirdPersonRemoteClientSystem.java
Labels: Bug, Multiplayer, Rendering

#3409 Upgrade to Gradle 4.7 for Java 10 compatibility (version parsing issue)
  gradle/wrapper/gradle-wrapper.properties
Labels: Logistics

#3425 Add fully qualified name (module:name) for biomes
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
Labels: UI

#3427 Small fix of margin on game details screen
  engine/src/main/resources/assets/ui/menu/gameDetailsScreen.ui
Labels: UI

#3428 Scrollable area refactor
  engine/src/main/java/org/terasology/rendering/nui/layouts/ScrollableArea.java
Labels: UI

#3429 Highlight active tab buttons
  engine/src/main/java/org/terasology/rendering/nui/widgets/UIButton.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/UITabBox.java
Labels: UI

#3439 Polymorphic Gson
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/gson/GsonTypeHandlerAdapterTest.java
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/gson/GsonTypeSerializationLibraryAdapterFactoryTest.java
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/gson/PolymorphicTypeAdapterFactoryTest.java
  engine/src/main/java/org/terasology/persistence/typeHandling/gson/GsonBuilderFactory.java
  engine/src/main/java/org/terasology/persistence/typeHandling/gson/PolymorphicTypeAdapterFactory.java
Labels: Api, Architecture

#3424 Up-Down-Enter keys support for UIList widget
  engine/src/main/java/org/terasology/rendering/nui/widgets/UIList.java
  engine/src/main/resources/assets/ui/menu/selectGameScreen.ui
Labels: UI

#3452 [Defect] Not always all modules are available for filtering
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Labels: Bug
