Repository MovingBlocks/Terasology, pull requests merged in 2018-12, with the labels that each got.

#3562 Added ProtobufSerialization Documentation
  engine/src/main/java/org/terasology/persistence/serializers/ProtobufSerializer.java
Labels: Documentation

#3540 Font color tests
  engine-tests/src/test/java/org/terasology/rendering/FontColorTest.java
Labels: UI

#3545 Add unit tests to the FontUnderline class
  engine-tests/src/test/java/org/terasology/rendering/FontUnderlineTest.java
Labels: UI

#3534 Fixed world saving error when running with ServerFacade
  engine/src/main/java/org/terasology/engine/subsystem/headless/mode/StateHeadlessSetup.java
Labels: Bug
