Repository MovingBlocks/Terasology, pull requests merged in 2019-04, with the labels that each got.

#3511 Allow modules limited API access to files
  engine/src/main/java/org/terasology/engine/module/ModuleInputStream.java
  engine/src/main/java/org/terasology/engine/module/ModuleOutputStream.java
  engine/src/main/java/org/terasology/engine/module/SandboxFileManager.java
  engine/src/main/java/org/terasology/engine/paths/PathManager.java
Labels: Architecture, Security

#3481 Animated tiles
  engine/src/main/java/org/terasology/rendering/dag/nodes/AlphaRejectBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/OpaqueBlocksNode.java
  engine/src/main/java/org/terasology/rendering/dag/nodes/WorldReflectionNode.java
  engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
  engine/src/main/java/org/terasology/rendering/primitives/ChunkMesh.java
  engine/src/main/java/org/terasology/rendering/primitives/ChunkTessellator.java
  engine/src/main/java/org/terasology/rendering/primitives/ChunkVertexFlag.java
  engine/src/main/java/org/terasology/world/block/Block.java
  engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java
  engine/src/main/java/org/terasology/world/block/loader/BlockFamilyDefinitionFormat.java
  engine/src/main/java/org/terasology/world/block/loader/SectionDefinitionData.java
  engine/src/main/java/org/terasology/world/block/shapes/BlockMeshPart.java
  engine/src/main/java/org/terasology/world/block/tiles/BlockTile.java
  engine/src/main/java/org/terasology/world/block/tiles/TileData.java
  engine/src/main/java/org/terasology/world/block/tiles/TileFormat.java
  engine/src/main/java/org/terasology/world/block/tiles/WorldAtlasImpl.java
  engine/src/main/resources/assets/shaders/chunk_frag.glsl
  engine/src/main/resources/assets/shaders/chunk_vert.glsl
  engine/src/main/resources/assets/textures/lavaStill.png
  modules/Core/assets/blockTiles/auto/AnimationTest.png
  modules/Core/assets/blockTiles/liquid/Lava.png
  modules/Core/assets/blocks/liquid/Lava.block
Labels: Api, Rendering

#3662 Update Modules.md
  docs/Modules.md
Labels: Documentation
