Repository MovingBlocks/Terasology, pull requests merged in 2019-03, with the labels that each got.

#3609 Add facet types and spawn logic for sparsely-valued spawn heights and sea level heights.
  engine/src/main/java/org/terasology/logic/spawner/AbstractSpawner.java
  engine/src/main/java/org/terasology/world/generation/facets/SpawnHeightFacet.java
  engine/src/main/java/org/terasology/world/generation/facets/StrictlySparseSeaLevelFacet.java
  engine/src/main/java/org/terasology/world/generation/facets/base/BaseSparseFacet2D.java
  engine/src/main/java/org/terasology/world/generation/facets/base/BaseStrictlySparseFieldFacet2D.java
Labels: Api, Architecture

#3621 world name appear when quick start game
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
Labels: UI

#3612 Make world generation random again
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameManifestProvider.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
Labels: Architecture, Bug

#3619 Add/Repair UI animations for in-game menus
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/DevToolsMenuScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/ExtraMenuScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/PauseMenu.java
Labels: UI

#3626 Fixed Issue #2921 and Additional Translation [Only Hindi Translation]
  engine/src/main/resources/assets/i18n/menu_hi.lang
Labels: UI

#3638 Added null checks when dependency is not found
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/moduleDetailsScreen/ModuleDetailsScreen.java
Labels: Bug, UI
