Repository MovingBlocks/Terasology, pull requests merged in 2019-08, with the labels that each got.

#3713 Fix APIScanner NPE when running MTE tests
  engine/src/main/java/org/terasology/input/binds/inventory/UseItemButton.java
  engine/src/main/java/org/terasology/input/binds/inventory/package-info.java
Labels: Bug, Logistics

#3718 Fix NPEs related to movable selections
  engine/src/main/java/org/terasology/logic/selection/LocalPlayerBlockSelectionByItemSystem.java
Labels: Bug, UI

#3726 TypeRegistry Optimization
  engine-tests/src/main/java/org/terasology/HeadlessEnvironment.java
  engine-tests/src/main/java/org/terasology/ModuleEnvironmentTest.java
  engine-tests/src/main/java/org/terasology/testUtil/ModuleManagerFactory.java
  engine-tests/src/test/java/org/terasology/reflection/TypeRegistryTest.java
  engine/src/main/java/org/terasology/engine/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java
  engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
  engine/src/main/java/org/terasology/reflection/TypeRegistry.java
  engine/src/main/java/org/terasology/reflection/internal/TypeRegistryImpl.java
  engine/src/main/java/org/terasology/utilities/ReflectionUtil.java
Labels: Architecture
