Repository MovingBlocks/Terasology, pull requests merged in 2019-07, with the labels that each got.

#3671 Improve performance of BlockMeshGeneratorSingleShape#generateChunkMesh
  engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
Labels: Performance, Rendering

#3666 Fixed OpenGL line width warning
  engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/rendering/logic/RegionOutlineRenderer.java
  engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
Labels: Bug, Rendering

#3708 Collective behavior trees
  .gitignore
  engine-tests/out/production/resources/assets/behaviors/BehaviorA.behavior
  engine-tests/out/production/resources/assets/behaviors/BehaviorB.behavior
  engine-tests/out/production/resources/assets/behaviors/BehaviorEmptyLookup.behavior
  engine-tests/out/production/resources/assets/behaviors/BehaviorLookup.behavior
  engine-tests/out/production/resources/assets/behaviors/BehaviorLookupB.behavior
  engine-tests/out/production/resources/assets/prefabs/inheritsComponent.prefab
  engine-tests/out/production/resources/assets/prefabs/multilevelInheritance.prefab
  engine-tests/out/production/resources/assets/prefabs/simple.prefab
  engine-tests/out/production/resources/assets/prefabs/withCollectionOfMappedContainers.prefab
  engine-tests/out/production/resources/assets/prefabs/withComponent.prefab
  engine-tests/out/production/resources/assets/prefabs/withComponentContainingOrderedMap.prefab
  engine-tests/out/production/resources/assets/prefabs/withListContainer.prefab
  engine-tests/out/production/resources/assets/prefabs/withListEnumContainer.prefab
  engine-tests/out/production/resources/module.txt
  engine-tests/out/test/resources/contextMenuBuilderInput.ui
  engine-tests/out/test/resources/gameManifest.json
  engine-tests/out/test/resources/jsonTreeConverterInput.json
  engine-tests/out/test/resources/logback.xml
  engine/src/main/java/org/terasology/logic/behavior/Callback.java
  engine/src/main/java/org/terasology/logic/behavior/CollectiveBehaviorComponent.java
  engine/src/main/java/org/terasology/logic/behavior/CollectiveBehaviorSystem.java
  engine/src/main/java/org/terasology/logic/behavior/CollectiveInterpreter.java
  engine/src/main/java/org/terasology/logic/behavior/DefaultCollectiveBehaviorTreeRunner.java
  engine/src/main/java/org/terasology/logic/behavior/Interpreter.java
  engine/src/main/java/org/terasology/logic/behavior/core/CollectiveBehaviorTreeRunner.java
Labels: Architecture, Content

#3711 Implement movable selection feature
  engine/src/main/java/org/terasology/logic/selection/LocalPlayerBlockSelectionByItemSystem.java
  engine/src/main/java/org/terasology/logic/selection/MovableSelectionEndEvent.java
  engine/src/main/java/org/terasology/logic/selection/MovableSelectionStartEvent.java
  engine/src/main/java/org/terasology/world/selection/BlockSelectionComponent.java
Labels: UI

#3712 Plug in a few missing BiomesAPI spots
  config/groovy/module.groovy
  docs/Modules.md
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/moduleDetailsScreen/ModuleDetailsScreen.java
Labels: Bug, Logistics

#3715 fix groovy module commands for engine modules
  config/groovy/common.groovy
Labels: Bug
