Repository MovingBlocks/Terasology, pull requests merged in 2019-10, with the labels that each got.

#3743 Bump Gradle to latest 4.x
  gradle/wrapper/gradle-wrapper.properties
Labels: Logistics

#3723 AutoConfig
  engine-tests/src/main/java/org/terasology/config/flexible/TestAutoConfig.java
  engine-tests/src/test/java/org/terasology/config/flexible/AutoConfigManagerTest.java
  engine-tests/src/test/java/org/terasology/config/flexible/AutoConfigSerializerTest.java
  engine-tests/src/test/java/org/terasology/config/flexible/AutoConfigTest.java
  engine-tests/src/test/java/org/terasology/config/flexible/internal/FlexibleConfigImplTest.java
  engine-tests/src/test/java/org/terasology/config/flexible/internal/SettingImplTest.java
  engine/src/main/java/org/terasology/audio/openAL/OpenALManager.java
  engine/src/main/java/org/terasology/config/AudioConfig.java
  engine/src/main/java/org/terasology/config/Config.java
  engine/src/main/java/org/terasology/config/RootConfig.java
  engine/src/main/java/org/terasology/config/flexible/AutoConfig.java
  engine/src/main/java/org/terasology/config/flexible/AutoConfigManager.java
  engine/src/main/java/org/terasology/config/flexible/AutoConfigSerializer.java
  engine/src/main/java/org/terasology/config/flexible/FlexibleConfig.java
  engine/src/main/java/org/terasology/config/flexible/FlexibleConfigManager.java
  engine/src/main/java/org/terasology/config/flexible/Setting.java
  engine/src/main/java/org/terasology/config/flexible/SettingArgument.java
  engine/src/main/java/org/terasology/config/flexible/SettingChangeListener.java
  engine/src/main/java/org/terasology/config/flexible/internal/FlexibleConfigImpl.java
  engine/src/main/java/org/terasology/config/flexible/internal/FlexibleConfigManagerImpl.java
  engine/src/main/java/org/terasology/config/flexible/internal/SettingBuilder.java
  engine/src/main/java/org/terasology/config/flexible/internal/SettingImpl.java
  engine/src/main/java/org/terasology/config/flexible/internal/SettingImplBuilder.java
  engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java
  engine/src/main/java/org/terasology/engine/paths/PathManager.java
  engine/src/main/java/org/terasology/engine/subsystem/common/ConfigurationSubsystem.java
  engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglAudio.java
  engine/src/main/java/org/terasology/reflection/reflect/ConstructorLibrary.java
  engine/src/main/java/org/terasology/registry/InjectionHelper.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/AudioSettingsScreen.java
  engine/src/main/java/org/terasology/utilities/ReflectionUtil.java
Labels: Api, Architecture

#3733 Add 'get-all' command to groovy script
  config/groovy/util.groovy
Labels: Bug, Logistics

#3735 Added kanji font pngs and updated Japanese menu text.
  engine/src/main/resources/assets/fonts/NotoSans-Regular.fnt
  engine/src/main/resources/assets/fonts/noto_sans_jp_hira_kana_kanji_0.png
  engine/src/main/resources/assets/fonts/noto_sans_jp_hira_kana_kanji_1.png
  engine/src/main/resources/assets/i18n/menu_ja.lang
Labels: UI

#3764 Upgrade Artifactory plugin to fix compatibility issue with latest Gradle version bump
  build.gradle
Labels: Bug, Logistics

#3770 Pass `context` directly to `loadConfig` method in AutoConfigManager
  engine/src/main/java/org/terasology/config/flexible/AutoConfigManager.java
Labels: Enhancement

#3650 Overlay rendering order fix
  engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
Labels: Bug, Rendering

#3777 Improve logging in module update script
  config/groovy/common.groovy
Labels: Enhancement

#3772 Add trunk blocks & associated logic
  engine/src/main/resources/assets/atlas/items.atlas
  engine/src/main/resources/assets/textures/items.png
  modules/Core/src/main/java/org/terasology/core/logic/trunk/TrunkComponent.java
  modules/Core/src/main/java/org/terasology/core/logic/trunk/TrunkPlacedEvent.java
  modules/Core/src/main/java/org/terasology/core/logic/trunk/TrunkSystem.java
  modules/Core/src/main/java/org/terasology/core/logic/trunk/package-info.java
Labels: Content
