Repository MovingBlocks/Terasology, pull requests merged in 2020-06, with the labels that each got.

#4010 feat: Improve block placement of ceiling-supporting family
  engine/src/main/java/org/terasology/world/block/family/CeilingSupportingHorizontalFamily.java
  engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
Labels: Enhancement

#4005 chore: more descriptive error message on spawn failure
  engine/src/main/java/org/terasology/logic/players/PlayerFactory.java
Labels: Stabilization

#3997 fix: prevent crash entering rendering settings with no renderers
  engine/src/main/java/org/terasology/engine/module/rendering/RenderingModuleRegistry.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/RenderingModuleSettingScreen.java
  engine/src/main/java/org/terasology/rendering/world/WorldRendererImpl.java
Labels: Bug, Rendering, UI

#3968 feat: Particle pool rendering
  engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
  engine/src/main/java/org/terasology/particles/ParticlePool.java
  engine/src/main/java/org/terasology/particles/ParticleSystemManagerImpl.java
  engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java
  engine/src/main/java/org/terasology/particles/updating/ParticleUpdaterImpl.java
  engine/src/main/java/org/terasology/rendering/assets/material/BaseMaterial.java
  engine/src/main/java/org/terasology/rendering/assets/shader/GLSLShaderFormat.java
  engine/src/main/java/org/terasology/rendering/assets/shader/ShaderData.java
  engine/src/main/java/org/terasology/rendering/opengl/GLSLShader.java
  engine/src/main/resources/assets/shaders/particle_frag.glsl
  engine/src/main/resources/assets/shaders/particle_geom.glsl
  engine/src/main/resources/assets/shaders/particle_vert.glsl
Labels: Enhancement, Rendering

#4019 fix(docs): replace some develop instructions with links to the wiki.
  .idea/dictionaries/kevint.xml
  README.markdown
Labels: Documentation

#4023 fix invisible skeletalmesh
  engine/src/main/java/org/terasology/rendering/logic/RegionOutlineRenderer.java
  engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
Labels: Blocker, Bug, Rendering

#4033 fix(Particles): disable particles, when driver or GPU not supports OpenGL 3.3
  engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java
  engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java
  engine/src/main/java/org/terasology/rendering/ShaderManagerLwjgl.java
Labels: Rendering

#4052 fix: security hassle from a plugin
  Jenkinsfile
Labels: Logistics

#4056 Don't serialize particle pools.
  engine/src/main/java/org/terasology/particles/components/ParticleEmitterComponent.java
  engine/src/main/java/org/terasology/persistence/typeHandling/coreTypes/ObjectFieldMapTypeHandler.java
Labels: Bug

#4057 Add informative popup if starting game without modules
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
Labels: UI

#3917 feat(JOML): Migrate Particle System
  engine/src/main/java/org/terasology/particles/ParticleData.java
  engine/src/main/java/org/terasology/particles/components/ParticleDataSpriteComponent.java
  engine/src/main/java/org/terasology/particles/components/affectors/AccelerationAffectorComponent.java
  engine/src/main/java/org/terasology/particles/components/generators/ColorRangeGeneratorComponent.java
  engine/src/main/java/org/terasology/particles/components/generators/PositionRangeGeneratorComponent.java
  engine/src/main/java/org/terasology/particles/components/generators/ScaleRangeGeneratorComponent.java
  engine/src/main/java/org/terasology/particles/components/generators/TextureOffsetGeneratorComponent.java
  engine/src/main/java/org/terasology/particles/components/generators/VelocityRangeGeneratorComponent.java
  engine/src/main/java/org/terasology/particles/functions/generators/ColorRangeGeneratorFunction.java
  engine/src/main/java/org/terasology/particles/functions/generators/TextureOffsetGeneratorFunction.java
  engine/src/main/java/org/terasology/particles/functions/generators/VelocityRangeGeneratorFunction.java
  engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java
  engine/src/main/java/org/terasology/particles/updating/ParticleUpdaterImpl.java
Labels: Architecture

#4058 Add setMaxIcons to UIIconBar
  engine/src/main/java/org/terasology/rendering/nui/widgets/UIIconBar.java
Labels: Enhancement, UI
