Repository MovingBlocks/Terasology, pull requests merged in 2020-10, with the labels that each got.

#4169 chore(JNA): update JNA to 5.6.0, remove com.sun.jna from jopenvr.jar
  engine/build.gradle
  engine/libs/jopenvr.jar
Labels: Bug, Logistics, Rendering

#4140 Chunk provider refactoring. Part 2.
  engine-tests/src/test/java/org/terasology/fixtures/TestBlockManager.java
  engine-tests/src/test/java/org/terasology/fixtures/TestChunkStore.java
  engine-tests/src/test/java/org/terasology/fixtures/TestStorageManager.java
  engine-tests/src/test/java/org/terasology/fixtures/TestWorldGenerator.java
  engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java
  engine-tests/src/test/java/org/terasology/world/chunks/pipeline/ChunkProcessingPipelineTest.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRemoteWorld.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
  engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java
  engine/src/main/java/org/terasology/utilities/concurrency/TaskMaster.java
  engine/src/main/java/org/terasology/world/chunks/ChunkProvider.java
  engine/src/main/java/org/terasology/world/chunks/internal/GeneratingChunkProvider.java
  engine/src/main/java/org/terasology/world/chunks/internal/ReadyChunkInfo.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/ChunkFinalizer.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/ConcurrentMapChunkCache.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LightMergingChunkFinalizer.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/RelevanceSystem.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/AbstractChunkTask.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkGenerationPipeline.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkProcessingInfo.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkProcessingPipeline.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkTask.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/PositionFuture.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/ShutdownChunkTask.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/stages/ChunkTask.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/stages/ChunkTaskProvider.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/stages/MultiplyRequirementChunkTask.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/stages/SingleChunkTask.java
  engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
  engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
  engine/src/main/java/org/terasology/world/propagation/LocalChunkView.java
  engine/src/main/java/org/terasology/world/propagation/light/LightMerger.java
Labels: Architecture, Performance

#4168 feat(JOML): add orientation for Rotation
  engine-tests/src/test/java/org/terasology/math/RotationTest.java
  engine/src/main/java/org/terasology/math/Rotation.java
Labels: Architecture

#4101 feat(JOML): Migrate side#getVector3i() to direction()
  engine-tests/src/test/java/org/terasology/math/SideTest.java
  engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
  engine/src/main/java/org/terasology/logic/location/ImmutableBlockLocation.java
  engine/src/main/java/org/terasology/math/ChunkMath.java
  engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
Labels: Architecture

#4173 docs: update module lineup list
  docs/Modules.md
Labels: Documentation

#4199 fix(nui): `InputSettings:onClose` out-of-bounds crash
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java
Labels: Bug

#4166 feat: remove Has/Cancel/Add DelayedActionEvent
  engine/src/main/java/org/terasology/logic/delay/AddDelayedActionEvent.java
  engine/src/main/java/org/terasology/logic/delay/CancelDelayedActionEvent.java
  engine/src/main/java/org/terasology/logic/delay/DelayedActionSystem.java
  engine/src/main/java/org/terasology/logic/delay/HasDelayedActionEvent.java
Labels: Api, Architecture

#4212 fix(gradle-server): restore missing suffix for jvmarg -Xmx
  facades/PC/build.gradle.kts
Labels: Bug

#4213 fix: AGS selection weirdness
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Labels: Bug

#4214 chore(chunkprovider): Streamline ChunkProvier
  engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkProcessingPipeline.java
  engine/src/main/java/org/terasology/world/propagation/LocalChunkView.java
Labels: Bug

#4219 fix(nui-input): access to `KeyboardDevice`
  engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
Labels: Bug

#4220 fix(screenshot): fix quad screenshots
  engine/src/main/java/org/terasology/rendering/opengl/fbms/DisplayResolutionDependentFbo.java
Labels: Bug

#4222 fix: moving on typing, typing keybind in console/chat
  engine/build.gradle
  engine/src/main/java/org/terasology/logic/chat/ChatSystem.java
  engine/src/main/java/org/terasology/logic/console/ConsoleSystem.java
Labels: Bug

#4227 chore: Archive COLLADA format
  engine/build.gradle
  engine/src/main/java/org/terasology/rendering/assets/mesh/ColladaMeshFormat.java
  engine/src/main/java/org/terasology/rendering/collada/ColladaLoader.java
  engine/src/main/java/org/terasology/rendering/collada/ColladaParseException.java
  engine/src/main/java/org/terasology/rendering/collada/ColladaSkeletalMeshLoader.java
  engine/src/main/resources/assets/materials/vertexColored.mat
  engine/src/main/resources/assets/shaders/vertexColoredMesh.info
  engine/src/main/resources/assets/shaders/vertexColoredMesh_frag.glsl
  engine/src/main/resources/assets/shaders/vertexColoredMesh_vert.glsl
Labels: Architecture, Logistics, Rendering, Stabilization

#4223 build: log Java version and JDK path with gradle warning.
  build.gradle
Labels: Enhancement
