Repository MovingBlocks/Terasology, pull requests merged in 2020-07, with the labels that each got.

#4066 always try loading classpath jars as modules
  engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
Labels: Architecture

#4029 feat(JOML): Migrate ChunkMath
  engine-tests/src/main/java/org/terasology/MapWorldProvider.java
  engine-tests/src/test/java/org/terasology/math/ChunkMathTest.java
  engine/src/main/java/org/terasology/math/ChunkMath.java
  engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
  engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
  engine/src/main/java/org/terasology/world/propagation/AbstractFullWorldView.java
  engine/src/main/java/org/terasology/world/propagation/LocalChunkView.java
Labels: Architecture

#4071 set fallback to engine:default rather than Behaviors:fallback
  engine/src/main/java/org/terasology/logic/behavior/core/BehaviorTreeBuilder.java
Labels: Bug

#4075 fix: Increase item pickup range
  engine/src/main/java/org/terasology/logic/characters/CharacterMovementComponent.java
  engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
Labels: Bug

#4078 fix/Make the height of the shapes derived from CharacterMovementComponents more consistent.
  engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
Labels: Physics

#4070 feat(JOML): migrate submersibleCamera
  engine/src/main/java/org/terasology/rendering/RenderHelper.java
  engine/src/main/java/org/terasology/rendering/cameras/SubmersibleCamera.java
Labels: Api

#4004 fix: gracefully catch and report errors that happen during game load
  engine/src/main/java/org/terasology/engine/modes/StateLoading.java
  engine/src/main/java/org/terasology/engine/modes/StateMainMenu.java
Labels: Stabilization

#4082 Add subprojects under `libs/` as included builds for easy substitution
  engine/build.gradle
  facades/PC/build.gradle
  libs/subprojects.gradle
Labels: Logistics

#4089 feat(FlowLayout): add option for vertical spacing
  engine/src/main/java/org/terasology/rendering/nui/layouts/FlowLayout.java
Labels: UI

#3902 partial port of kinematicCharacterMover
  engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java
  engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
Labels: Architecture

#4064 fix(GameProvider): prevent creating game with duplicate name
  engine-tests/src/test/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProviderTest.java
  engine-tests/src/test/resources/gameManifest.json
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameManifestProvider.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/NewGameScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProvider.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/NumberedGameName.java
Labels: Bug, UI

#4097 feat(AGS): by default show only locally present modules
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Labels: Enhancement, UI

#4098 fix: Actually register InputSystem as system
  engine/src/main/java/org/terasology/input/InputSystem.java
Labels: Bug

#4046 make `libs/` use included builds instead of subprojects
  facades/subprojects.settings.gradle
  libs/subprojects.gradle
  libs/subprojects.settings.gradle
  metas/subprojects.settings.gradle
  modules/subprojects.settings.gradle
  settings.gradle
Labels: Logistics

#4095 feat: Add BeforeAfterEvent
  engine/src/main/java/org/terasology/entitySystem/event/BeforeAfterEvent.java
Labels: Api, Enhancement

#4100 docs: Improve docs for BeforeAfterEvent
  engine/src/main/java/org/terasology/entitySystem/event/BeforeAfterEvent.java
Labels: Bug, Documentation

#4063 doc: Add docs and contracts for AbstractValueModifiableEvent
  engine/src/main/java/org/terasology/entitySystem/event/AbstractValueModifiableEvent.java
Labels: Bug, Documentation, WIP

#4090 feat(FlowLayout): Add option for horizontal spacing
  engine/src/main/java/org/terasology/rendering/nui/layouts/FlowLayout.java
Labels: Enhancement, UI

#4106 fix(tests): reduce timing-based test failures on CI
  engine-tests/src/test/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProviderTest.java
Labels: Bug

#4093 fixed the load latest configuration
  engine/src/main/java/org/terasology/engine/TerasologyEngine.java
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Bug

#4099 Make EntityRef.copy and related things deeper
  engine/src/main/java/org/terasology/entitySystem/entity/EntityRef.java
  engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
  engine/src/main/java/org/terasology/entitySystem/metadata/ComponentFieldMetadata.java
  engine/src/main/java/org/terasology/entitySystem/metadata/ComponentLibrary.java
  engine/src/main/java/org/terasology/entitySystem/metadata/ComponentMetadata.java
  engine/src/main/java/org/terasology/entitySystem/metadata/EventMetadata.java
  engine/src/main/java/org/terasology/entitySystem/metadata/ReplicatedFieldMetadata.java
  engine/src/main/java/org/terasology/reflection/copy/strategy/EntityCopyStrategy.java
  engine/src/main/java/org/terasology/reflection/metadata/ClassMetadata.java
  engine/src/main/java/org/terasology/reflection/metadata/DefaultClassMetadata.java
  engine/src/main/java/org/terasology/reflection/metadata/FieldMetadata.java
  engine/src/main/java/org/terasology/rendering/nui/internal/WidgetMetadata.java
Labels: Architecture
