Repository MovingBlocks/Terasology, pull requests merged in 2020-08, with the labels that each got.

#4113 fix: Increase connection timeout for clients as heavier module setups can take a while
  engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java
Labels: Bug, Performance

#4094 feat: Add ModifiableValue type
  engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/ModifiableValueTypeHandler.java
  engine/src/main/java/org/terasology/utilities/modifiable/ModifiableValue.java
Labels: Enhancement

#4119 feat: new run config to recreate the most recently launched game auto…
  .idea/runConfigurations/TerasologyPC__recreate_latest_.xml
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Logistics

#4111 feat(JOML): Migrate RegionOutlineRenderer
  engine/src/main/java/org/terasology/rendering/logic/RegionOutlineRenderer.java
Labels: Architecture

#4102 feat(JOML): migrate GazeMountPointComponent
  engine/src/main/java/org/terasology/logic/characters/GazeAuthoritySystem.java
  engine/src/main/java/org/terasology/logic/characters/GazeMountPointComponent.java
  engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
Labels: Architecture

#3961 feat(JOML): migrate ChunkViewCore
  engine/src/main/java/org/terasology/world/chunks/ChunkConstants.java
  engine/src/main/java/org/terasology/world/internal/ChunkViewCore.java
  engine/src/main/java/org/terasology/world/internal/ChunkViewCoreImpl.java
Labels: Architecture

#4026 feat(JOML): Migrate MeshRenderer
  engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java
Labels: Architecture

#3953 fix: allow game to quit without waiting for registry updater thread
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Labels: Bug, Research

#4132 chore: Extract relevance code for ChunkProvider's to RelevanceSystem
  engine-tests/src/test/java/org/terasology/world/propagation/BetweenChunkPropagationTest.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
  engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
  engine/src/main/java/org/terasology/rendering/world/viewDistance/ServerViewDistanceSystem.java
  engine/src/main/java/org/terasology/world/chunks/ChunkProvider.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/RelevanceSystem.java
  engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
Labels: Enhancement, Multiplayer, Rendering
