Repository MovingBlocks/Terasology, pull requests merged in 2020-09, with the labels that each got.

#4122 perf: simplified check for rendering ready.
  engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
Labels: Performance, Rendering

#4141 fix: Gradley weirdness about a Directory/DirectoryProperty thing
  .idea/misc.xml
  facades/PC/build.gradle
Labels: Logistics

#4148 fix(performance): optimize ModuleEnvironmentSandbox.getSubTypeIdentifier
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/reflection/ModuleEnvironmentSandboxTest.java
  engine/src/main/java/org/terasology/persistence/typeHandling/reflection/ModuleEnvironmentSandbox.java
  engine/src/main/java/org/terasology/persistence/typeHandling/reflection/ReflectionsSandbox.java
  engine/src/main/java/org/terasology/persistence/typeHandling/reflection/SerializationSandbox.java
Labels: Blocker, Bug, Multiplayer, Performance

#4160 feat: increase default window size to 8:5 WXGA
  engine/src/main/resources/default.cfg
Labels: Enhancement, UI
