Repository MovingBlocks/Terasology, pull requests merged in 2020-01, with the labels that each got.

#3805 Switched URL to a URI for better mapping.
  engine/src/main/java/org/terasology/engine/module/ModuleInstaller.java
  engine/src/main/java/org/terasology/utilities/download/MultiFileDownloader.java
Labels: Documentation, Enhancement, Security

#3589 Merge pull request #3589 from Adrijaned/loadProcessDoc
  engine/src/main/java/org/terasology/engine/ComponentSystemManager.java
  engine/src/main/java/org/terasology/engine/modes/SingleStepLoadProcess.java
  engine/src/main/java/org/terasology/engine/modes/StateLoading.java
  engine/src/main/java/org/terasology/engine/modes/StepBasedLoadProcess.java
  engine/src/main/java/org/terasology/engine/modes/VariableStepLoadProcess.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/AwaitCharacterSpawn.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/CacheBlocks.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/CacheTextures.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/CreateRemoteWorldEntity.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/CreateWorldEntity.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/EnsureSaveGameConsistency.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseBlockTypeEntities.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseCommandSystem.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseComponentSystemManager.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseEntitySystem.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseGraphics.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialisePhysics.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRecordAndReplay.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseRemoteWorld.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseSystems.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorld.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/InitialiseWorldGenerator.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/JoinServer.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadEntities.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadExtraBlockData.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/LoadPrefabs.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/PostBeginSystems.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/PreBeginSystems.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/PrepareWorld.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/ProcessBlockPrefabs.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterBlockFamilies.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterBlocks.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterInputSystem.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterMods.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/RegisterSystems.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/SetupLocalPlayer.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/SetupRemotePlayer.java
  engine/src/main/java/org/terasology/engine/modes/loadProcesses/StartServer.java
  engine/src/main/java/org/terasology/persistence/internal/ReadWriteStorageManager.java
  engine/src/main/java/org/terasology/rendering/world/WorldRenderer.java
Labels: Api, Architecture, Documentation

#3802 Restore pre-BiomeAPI foliage shading
  engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGenerator.java
  engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
  engine/src/main/java/org/terasology/rendering/primitives/ChunkTessellator.java
  engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java
  engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
  engine/src/main/java/org/terasology/world/block/Block.java
  engine/src/main/java/org/terasology/world/block/BlockColorSource.java
  engine/src/main/java/org/terasology/world/block/DefaultColorSource.java
  engine/src/main/java/org/terasology/world/block/internal/BlockBuilder.java
  engine/src/main/java/org/terasology/world/block/loader/BlockFamilyDefinitionFormat.java
  engine/src/main/java/org/terasology/world/block/loader/SectionDefinitionData.java
  engine/src/main/java/org/terasology/world/block/shapes/BlockMeshPart.java
  engine/src/main/resources/assets/shaders/chunk_frag.glsl
Labels: Bug, Enhancement, Rendering

#3821 fixed threading issue with discord RPC
  engine/src/main/java/org/terasology/engine/subsystem/rpc/DiscordRPCSubSystem.java
Labels: Enhancement, Performance
