Repository MovingBlocks/Terasology, pull requests merged in 2020-05, with the labels that each got.

#3921 feat(groovyw): add command to create dependency dot file
  config/groovy/common.groovy
  config/groovy/module.groovy
  config/groovy/util.groovy
Labels: Enhancement

#3822 Adjust game selection screen to use world generator's display name
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectionScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
Labels: UI

#3923 feat(JOML): Migrate BlockEntityRegistry
  engine/src/main/java/org/terasology/world/BlockEntityRegistry.java
  engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
Labels: Architecture

#3939 feat: Particle Pool Sharing
  engine/src/main/java/org/terasology/particles/ParticleSystemManagerImpl.java
  engine/src/main/java/org/terasology/particles/updating/ParticleUpdaterImpl.java
Labels: Enhancement, Performance, Rendering

#3913 fix: Add type handler for `Class<? extends Component>`
  engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
  engine/src/main/java/org/terasology/persistence/typeHandling/TypeHandlerLibrary.java
  engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/ComponentClassTypeHandler.java
  engine/src/main/java/org/terasology/persistence/typeHandling/extensionTypes/factories/ComponentClassTypeHandlerFactory.java
  engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
Labels: Bug

#3952 chore(groovyw): Add command to list local modules
  config/groovy/util.groovy
Labels: Support

#3956 fix: add 'templates/build.gradle' to build artifacts
  Jenkinsfile
Labels: Blocker, Logistics

#3955 chore: remove stray compiler outputs
  .gitignore
  engine-tests/out/production/resources/assets/behaviors/BehaviorA.behavior
  engine-tests/out/production/resources/assets/behaviors/BehaviorB.behavior
  engine-tests/out/production/resources/assets/behaviors/BehaviorEmptyLookup.behavior
  engine-tests/out/production/resources/assets/behaviors/BehaviorLookup.behavior
  engine-tests/out/production/resources/assets/behaviors/BehaviorLookupB.behavior
  engine-tests/out/production/resources/assets/prefabs/inheritsComponent.prefab
  engine-tests/out/production/resources/assets/prefabs/multilevelInheritance.prefab
  engine-tests/out/production/resources/assets/prefabs/simple.prefab
  engine-tests/out/production/resources/assets/prefabs/withCollectionOfMappedContainers.prefab
  engine-tests/out/production/resources/assets/prefabs/withComponent.prefab
  engine-tests/out/production/resources/assets/prefabs/withComponentContainingOrderedMap.prefab
  engine-tests/out/production/resources/assets/prefabs/withListContainer.prefab
  engine-tests/out/production/resources/assets/prefabs/withListEnumContainer.prefab
  engine-tests/out/production/resources/module.txt
  engine-tests/out/test/resources/contextMenuBuilderInput.ui
  engine-tests/out/test/resources/gameManifest.json
  engine-tests/out/test/resources/jsonTreeConverterInput.json
  engine-tests/out/test/resources/logback.xml
Labels: Bug

#3971 feat: disable transient dependencies
  templates/build.gradle
Labels: Stabilization

#3954 add IntelliJ configuration
  .gitignore
  .idea/.gitignore
  .idea/checkstyle-idea.xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/copyright/TerasologyEngine.xml
  .idea/copyright/profiles_settings.xml
  .idea/dictionaries/kevint.xml
  .idea/externalDependencies.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/runConfigurations/All_in_NameGenerator.xml
  .idea/runConfigurations/TeraEd__rendering_editor_.xml
  .idea/runConfigurations/TerasologyPC.xml
  .idea/runConfigurations/TerasologyPC__2nd_client_.xml
  .idea/runConfigurations/TerasologyPC__3rd_client_.xml
  .idea/runConfigurations/TerasologyPC__CR_enabled_.xml
  .idea/runConfigurations/TerasologyPC__EXTREME_8GB_.xml
  .idea/runConfigurations/TerasologyPC__Headless_.xml
  .idea/runConfigurations/TerasologyPC__Java_FlightRecorder_.xml
  .idea/runConfigurations/TerasologyPC__Splash_disabled_.xml
  .idea/runConfigurations/TerasologyPC__load_latest_.xml
  .idea/runConfigurations/TerasologyPC__no_audio_.xml
  .idea/runConfigurations/TerasologyPC__no_saves_.xml
  .idea/runConfigurations/TerasologyPC__permissive_security_.xml
  .idea/runConfigurations/engine_tests_with_JaCoCo.xml
  .idea/runConfigurations/extract_requirements.xml
  .idea/runConfigurations/game__gradle_.xml
  .idea/scopes/NUI.xml
  .idea/scopes/Terasology_Libs.xml
  .idea/scopes/gradles.xml
  .idea/scopes/mod_assets.xml
  .idea/scopes/mod_sources.xml
  .idea/startup.xml
  build.gradle
  config/gradle/ide.gradle
Labels: Enhancement, Logistics

#3974 Fixes for #3954
  .idea/.gitignore
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/runConfigurations/All_in_NameGenerator.xml
  .idea/runConfigurations/TeraEd__rendering_editor_.xml
  .idea/runConfigurations/TerasologyPC.xml
  .idea/runConfigurations/TerasologyPC__2nd_client_.xml
  .idea/runConfigurations/TerasologyPC__3rd_client_.xml
  .idea/runConfigurations/TerasologyPC__CR_enabled_.xml
  .idea/runConfigurations/TerasologyPC__EXTREME_8GB_.xml
  .idea/runConfigurations/TerasologyPC__Headless_.xml
  .idea/runConfigurations/TerasologyPC__Java_FlightRecorder_.xml
  .idea/runConfigurations/TerasologyPC__Splash_disabled_.xml
  .idea/runConfigurations/TerasologyPC__load_latest_.xml
  .idea/runConfigurations/TerasologyPC__no_audio_.xml
  .idea/runConfigurations/TerasologyPC__no_saves_.xml
  .idea/runConfigurations/TerasologyPC__permissive_security_.xml
  .idea/runConfigurations/engine_tests_with_JaCoCo.xml
  README.markdown
Labels: Bug

#3973 feat: Only show "augmentation" modules initially
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Labels: Enhancement, Stabilization, UI

#3977 feat: Add updateComponent and upsertComponent functional methods
  engine/src/main/java/org/terasology/entitySystem/MutableComponentContainer.java
Labels: Api, Documentation, Enhancement

#3980 build(idea): Import classes instead of fully qualified names
  .idea/codeStyles/Project.xml
Labels: Logistics

#3937 Change how LWJGL path is set. Improves compat with newer JRE
  .idea/runConfigurations/TerasologyPC__permissive_security_.xml
  engine/src/main/java/org/terasology/utilities/LWJGLHelper.java
  engine/src/main/java/org/terasology/utilities/NativeHelper.java
  facades/PC/build.gradle
Labels: Enhancement

#3986 fix: Prevent NPE in ModuleDetailsScreen
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/moduleDetailsScreen/ModuleDetailsScreen.java
Labels: Bug

#3983 fix: Respawn dead player after exiting the game
  engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
Labels: Bug

#3970 maint: upgrade gradle to 6.4 from 6.0
  .idea/codeStyles/Project.xml
  build.gradle
  config/gradle/common.gradle
  config/gradle/publish.gradle
  config/groovy/module.groovy
  engine-tests/build.gradle
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/modes/StateMainMenu.java
  engine/src/main/java/org/terasology/rendering/nui/internal/LwjglCanvasRenderer.java
  facades/PC/build.gradle
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
  facades/TeraEd/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/groovy-wrapper.jar
  gradlew
  gradlew.bat
  groovyw
  groovyw.bat
  modules/subprojects.gradle
  templates/build.gradle
  templates/facades.gradle
Labels: Enhancement, Logistics

#3991 build(templates): Add JUnit 5 params dependency
  templates/build.gradle
Labels: Logistics

#3987 feat: BlockFamily API enhancement
  engine/src/main/java/org/terasology/world/block/family/AttachedToSurfaceFamily.java
  engine/src/main/java/org/terasology/world/block/family/BlockFamily.java
  engine/src/main/java/org/terasology/world/block/family/BlockPlacementData.java
  engine/src/main/java/org/terasology/world/block/family/FreeformFamily.java
  engine/src/main/java/org/terasology/world/block/family/HorizontalFamily.java
  engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java
  engine/src/main/java/org/terasology/world/block/family/SymmetricFamily.java
  engine/src/main/java/org/terasology/world/block/items/BlockItemSystem.java
Labels: Api, Enhancement

#3978 feat: Ceiling BlockFamily
  engine/src/main/java/org/terasology/math/Rotation.java
  engine/src/main/java/org/terasology/world/block/BlockBuilderHelper.java
  engine/src/main/java/org/terasology/world/block/family/CeilingSupportingHorizontalFamily.java
Labels: Api, Enhancement

#4006 refactor(BlockItemFactory): remove code dupes; add doc; retain components
  engine/src/main/java/org/terasology/logic/common/RetainComponentsComponent.java
  engine/src/main/java/org/terasology/world/block/items/BlockItemFactory.java
Labels: Bug, Documentation, Enhancement
