Repository MovingBlocks/Terasology, pull requests merged in 2020-03, with the labels that each got.

#3847 Minor Gradle dependency tweak
  engine/build.gradle
Labels: Logistics, Security

#3858 Modified search to show if an asset is broken
  engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java
Labels: Bug

#3860 Multipayer Respawn Crash Bug Fix
  engine/src/main/java/org/terasology/audio/system/AudioSystem.java
  engine/src/main/java/org/terasology/entitySystem/sectors/SectorUtil.java
  engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java
  engine/src/main/java/org/terasology/logic/characters/events/ActivationPredicted.java
  engine/src/main/java/org/terasology/logic/common/ActivateEvent.java
  engine/src/main/java/org/terasology/logic/players/LocalPlayer.java
  engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
  engine/src/main/java/org/terasology/network/internal/NetClient.java
  engine/src/main/java/org/terasology/persistence/internal/AbstractStorageManager.java
  engine/src/main/java/org/terasology/persistence/internal/PlayerStoreInternal.java
  engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
  engine/src/main/java/org/terasology/physics/bullet/EntityMotionState.java
  engine/src/main/java/org/terasology/rendering/logic/FloatingTextRenderer.java
  engine/src/main/java/org/terasology/rendering/logic/MeshRenderer.java
  engine/src/main/java/org/terasology/world/chunks/internal/ChunkRelevanceRegion.java
  modules/Core/src/main/java/org/terasology/logic/actions/ExplosionAuthoritySystem.java
Labels: Bug, Multiplayer, Needs Info

#3873 Fixed UI bug at Advanced Game Setup window, Issue #3818
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
Labels: Bug, UI
