Repository MovingBlocks/Terasology, pull requests merged in 2020-12, with the labels that each got.

#4294 chore: remove some of the most noisy debug logs
  engine/src/main/java/org/terasology/entitySystem/event/internal/EventSystemImpl.java
  engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
  engine/src/main/java/org/terasology/logic/nameTags/PlayerNameTagSystem.java
  engine/src/main/java/org/terasology/logic/players/ThirdPersonRemoteClientSystem.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
  facades/PC/src/main/resources/logback.xml
Labels: Stabilization

#4293 feat: replace deprecated md5 assets with new gltf floating cube
  engine/src/main/resources/assets/animations/floatingCubeIdle.md5anim
  engine/src/main/resources/assets/prefabs/defaultVisualCharacter.prefab
  engine/src/main/resources/assets/prefabs/floatingCube.prefab
  engine/src/main/resources/assets/skeletalMesh/floatingCube.gltf
  engine/src/main/resources/assets/skeletalMesh/floatingCube.md5mesh
Labels: Bug

#4297 fix(world/chunks): make GenerateQueueEntity as Concurrent Collection
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
Labels: Bug

#4280 perf(chunkprovider): add sorting for incoming request on chunk loading/generation.
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkProcessingPipeline.java
Labels: Performance

#4299 fix: dispose physic's natives, stop threads.
  engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java
  engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkProcessingPipeline.java
Labels: Bug

#4298 fix: reduce volume and overmodulation of main theme
  engine/src/main/java/org/terasology/config/AudioConfig.java
  engine/src/main/resources/assets/music/MenuTheme.ogg
  engine/src/main/resources/default.cfg
Labels: Enhancement

#4301 fix(BlockRegion): correct center calculation for BlockRegion
  engine/src/main/java/org/terasology/world/block/BlockRegion.java
Labels: Bug

#4307 ci(subsystems): Make TypeHandlerLibrary publishable with engine's version
  subsystems/TypeHandlerLibrary/build.gradle.kts
Labels: Logistics

#4279 feat(JOML): migrate `character` package events and systems
  engine/src/main/java/org/terasology/logic/characters/CharacterImpulseEvent.java
  engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java
  engine/src/main/java/org/terasology/logic/characters/CharacterSoundSystem.java
  engine/src/main/java/org/terasology/logic/characters/CharacterStateEvent.java
  engine/src/main/java/org/terasology/logic/characters/ClientCharacterPredictionSystem.java
  engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
  engine/src/main/java/org/terasology/logic/characters/ServerCharacterPredictionSystem.java
  engine/src/main/java/org/terasology/logic/characters/events/CollisionEvent.java
  engine/src/main/java/org/terasology/logic/characters/events/HorizontalCollisionEvent.java
  engine/src/main/java/org/terasology/logic/characters/events/VerticalCollisionEvent.java
  engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
  engine/src/main/java/org/terasology/physics/events/MovedEvent.java
  engine/src/main/java/org/terasology/recording/CharacterStateEventPositionMap.java
Labels: Enhancement

#4325 add missing absolute value for box collider extent
  engine/src/main/java/org/terasology/physics/bullet/shapes/BulletBoxShape.java
Labels: Bug

#4321 fix!(BlockRegion): Rewrite of BlockRegion
  engine-tests/src/test/java/org/terasology/math/BlockRegionTest.java
  engine-tests/src/test/java/org/terasology/math/ChunkMathTest.java
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/mathTypes/BlockRegionTypeHandlerTest.java
  engine-tests/src/test/java/org/terasology/world/block/BlockRegionIterableTest.java
  engine-tests/src/test/java/org/terasology/world/block/BlockRegionTest.java
  engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java
  engine/src/main/java/org/terasology/math/ChunkMath.java
  engine/src/main/java/org/terasology/math/JomlUtil.java
  engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/BlockRegionTypeHandler.java
  engine/src/main/java/org/terasology/world/block/BlockRegion.java
  engine/src/main/java/org/terasology/world/block/BlockRegionIterable.java
  engine/src/main/java/org/terasology/world/block/BlockRegions.java
  engine/src/main/java/org/terasology/world/block/regions/BlockRegionComponent.java
  engine/src/main/java/org/terasology/world/propagation/StandardBatchPropagator.java
Labels: Api, Architecture

#4039 remove snapshot-or-not logic from gradle configuration
  .idea/dictionaries/kevint.xml
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/terasology-module.gradle.kts
  config/gradle/publish.gradle
  engine/build.gradle
Labels: Blocker, Logistics

#4326 refactor!(BlockRegion): full API overhaul
  engine-tests/src/test/java/org/terasology/math/ChunkMathTest.java
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/mathTypes/BlockRegionTypeHandlerTest.java
  engine-tests/src/test/java/org/terasology/world/block/BlockRegionIterableTest.java
  engine-tests/src/test/java/org/terasology/world/block/BlockRegionTest.java
  engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java
  engine/src/main/java/org/terasology/math/ChunkMath.java
  engine/src/main/java/org/terasology/math/JomlUtil.java
  engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/BlockRegionTypeHandler.java
  engine/src/main/java/org/terasology/world/block/BlockRegion.java
  engine/src/main/java/org/terasology/world/block/BlockRegionIterable.java
  engine/src/main/java/org/terasology/world/block/BlockRegionc.java
  engine/src/main/java/org/terasology/world/block/BlockRegions.java
  engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java
  engine/src/main/java/org/terasology/world/block/regions/BlockRegionSystem.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
  engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
  engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
  engine/src/main/java/org/terasology/world/propagation/StandardBatchPropagator.java
Labels: Api, Architecture, Documentation

#4330 chore(gradle): remove mavenLocal from project repositories
  build.gradle
  config/gradle/common.gradle
Labels: Logistics

#4332 doc: add system requirements to README
  README.markdown
Labels: Documentation

#4313 fix(world): Compute border requests from rasterizers and `@Updates` annotations.
  engine/src/main/java/org/terasology/world/generation/Border3D.java
  engine/src/main/java/org/terasology/world/generation/WorldBuilder.java
Labels: Bug

#4050 feat: add BlockArea to replace Rect2i
  engine-tests/src/test/java/org/terasology/world/block/BlockAreaTest.java
  engine/src/main/java/org/terasology/world/block/BlockArea.java
  engine/src/main/java/org/terasology/world/block/BlockAreac.java
Labels: WIP

#4337 fix: casing fix for homedir arg from Gradle
  facades/PC/build.gradle.kts
Labels: Bug, Logistics

#4342 build: save build time by not checking jcenter for terasology dependencies
  config/gradle/common.gradle
Labels: Logistics, Performance

#4352 fix(#4319): add attchmentSide to getBlockForPlacement
  engine/src/main/java/org/terasology/world/block/family/MultiConnectFamily.java
Labels: Bug
