Repository MovingBlocks/Terasology, pull requests merged in 2020-11, with the labels that each got.

#4125 chore(settings): disable identity service login ui features
  engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java
  engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui
Labels: UI

#4229 fix(menu): remove notification to configure identity service
  engine/src/main/java/org/terasology/identity/storageServiceClient/InitializeFromTokenAction.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MainMenuScreen.java
  engine/src/main/resources/assets/i18n/menu.lang
  engine/src/main/resources/assets/i18n/menu_cs.lang
  engine/src/main/resources/assets/i18n/menu_en.lang
  engine/src/main/resources/assets/i18n/menu_fr.lang
  engine/src/main/resources/assets/i18n/menu_hi.lang
  engine/src/main/resources/assets/i18n/menu_pl.lang
  engine/src/main/resources/assets/i18n/menu_sq.lang
  engine/src/main/resources/assets/i18n/menu_uk.lang
  engine/src/main/resources/assets/ui/menu/mainMenuScreen.ui
Labels: UI

#4121 fix: Reloading .ui file for screens during game
  engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java
Labels: Bug

#4232 chore: change texture file for 'engine:gui' atlas (crosshair-only)
  .idea/.gitignore
  engine/src/main/resources/assets/atlas/gui.atlas
  engine/src/main/resources/assets/textures/crosshair.png
  engine/src/main/resources/assets/textures/gui.png
Labels: UI

#4239 chore: bump dependency on splash screen to a fully released version
  engine/build.gradle
Labels: Logistics, UI

#4241 Fix not killed process.
  engine/src/main/java/org/terasology/world/chunks/pipeline/ChunkProcessingPipeline.java
Labels: Bug

#3571 feat: Add AFK state for players in multiplayer
  engine/src/main/java/org/terasology/logic/afk/AfkAuthoritySystem.java
  engine/src/main/java/org/terasology/logic/afk/AfkClientSystem.java
  engine/src/main/java/org/terasology/logic/afk/AfkComponent.java
  engine/src/main/java/org/terasology/logic/afk/AfkDetectEvent.java
  engine/src/main/java/org/terasology/logic/afk/AfkEvent.java
  engine/src/main/java/org/terasology/logic/afk/AfkRequest.java
  engine/src/main/java/org/terasology/logic/afk/AfkScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/OnlinePlayersOverlay.java
  engine/src/main/resources/assets/prefabs/player/client.prefab
  engine/src/main/resources/assets/ui/afk.ui
Labels: Api, Multiplayer, UI

#4245 Extract "run game" task configurations
  facades/PC/build.gradle.kts
Labels: Enhancement, Logistics

#4246 fix(skeletal-mesh-scaling): add scaling for skeletal-meshes
  engine/src/main/java/org/terasology/rendering/logic/SkeletonRenderer.java
Labels: Bug, Rendering

#4247 fix: index out of bounds in `GLTFAnimationFormat`
  engine/src/main/java/org/terasology/rendering/gltf/GLTFAnimationFormat.java
Labels: Bug

#4233 feature(subsystems): extract DiscordRPCSubSystem
  engine/build.gradle
  engine/src/main/java/org/terasology/config/PlayerConfig.java
  engine/src/main/java/org/terasology/entitySystem/systems/DiscordRPCSystem.java
  engine/src/main/java/org/terasology/logic/afk/AfkClientSystem.java
  engine/src/main/java/org/terasology/rendering/assets/atlas/AtlasFormat.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/PlayerSettingsScreen.java
  facades/PC/build.gradle.kts
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
  subsystems/DiscordRPC/README.MD
  subsystems/DiscordRPC/build.gradle.kts
  subsystems/DiscordRPC/src/main/java/org/terasology/engine/subsystem/discordrpc/DiscordRPCSubSystem.java
  subsystems/DiscordRPC/src/main/java/org/terasology/engine/subsystem/discordrpc/DiscordRPCSystem.java
  subsystems/README.MD
  subsystems/subprojects.settings.gradle
Labels: Api, Architecture, Enhancement

#4250 feat(rendering): Adjust minimal amount of daylight at night
  engine/src/main/java/org/terasology/rendering/backdrop/Skysphere.java
Labels: Rendering

#4252 fix: reduce default mouse sensitivity from 0.75 to 0.25
  engine/src/main/resources/default.cfg
Labels: Bug

#4253 feat: start first game day at sunrise
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/GameManifestProvider.java
  engine/src/main/java/org/terasology/world/time/WorldTime.java
Labels: Enhancement

#4254 fix: reverse order of notification in PojoEntityManager
  engine/src/main/java/org/terasology/entitySystem/entity/internal/PojoEntityManager.java
Labels: Architecture, Bug

#4256 fix: InputSystem#getInputsForBindButton was throwing NPE
  engine/src/main/java/org/terasology/input/InputSystem.java
Labels: Bug

#4258 feat(MutableComponentContainer): Handle 'null' values in [update|upsert]Component
  engine/src/main/java/org/terasology/entitySystem/MutableComponentContainer.java
Labels: Enhancement

#4224 feat: Upgrade Netty to version 4
  engine/build.gradle
  engine/src/main/java/org/terasology/network/ServerInfoService.java
  engine/src/main/java/org/terasology/network/internal/ClientConnectionHandler.java
  engine/src/main/java/org/terasology/network/internal/ClientHandler.java
  engine/src/main/java/org/terasology/network/internal/ClientHandshakeHandler.java
  engine/src/main/java/org/terasology/network/internal/MetricRecordingHandler.java
  engine/src/main/java/org/terasology/network/internal/NetClient.java
  engine/src/main/java/org/terasology/network/internal/NetworkSystemImpl.java
  engine/src/main/java/org/terasology/network/internal/ServerConnectionHandler.java
  engine/src/main/java/org/terasology/network/internal/ServerHandler.java
  engine/src/main/java/org/terasology/network/internal/ServerHandshakeHandler.java
  engine/src/main/java/org/terasology/network/internal/ServerImpl.java
  engine/src/main/java/org/terasology/network/internal/ServerInfoRequestHandler.java
  engine/src/main/java/org/terasology/network/internal/pipelineFactory/InfoRequestPipelineFactory.java
  engine/src/main/java/org/terasology/network/internal/pipelineFactory/TerasologyClientPipelineFactory.java
  engine/src/main/java/org/terasology/network/internal/pipelineFactory/TerasologyServerPipelineFactory.java
Labels: Enhancement, Logistics

#4257 chore: make older engine builds in Jenkins prune their attached artifacts + minor quality tweaks
  Jenkinsfile
Labels: Logistics

#4264 doc: fix some JavaDoc errors
  engine/src/main/java/org/terasology/config/BindsConfig.java
  engine/src/main/java/org/terasology/entitySystem/entity/internal/EntityInfoComponent.java
  engine/src/main/java/org/terasology/rendering/world/viewDistance/ViewDistanceChangedEvent.java
Labels: Documentation

#4260 feat(JOML): migrate monitoring
  engine/src/main/java/org/terasology/monitoring/chunk/ChunkMonitor.java
  engine/src/main/java/org/terasology/monitoring/chunk/ChunkMonitorEntry.java
  engine/src/main/java/org/terasology/monitoring/chunk/ChunkMonitorEvent.java
  engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java
  engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplayEvent.java
  engine/src/main/java/org/terasology/rendering/world/ChunkMeshUpdateManager.java
Labels: Enhancement

#4259 feat(JOML): migrate `InputSystem` and events
  engine/src/main/java/org/terasology/input/InputSystem.java
  engine/src/main/java/org/terasology/input/events/InputEvent.java
  engine/src/main/java/org/terasology/input/events/LeftMouseDownButtonEvent.java
  engine/src/main/java/org/terasology/input/events/LeftMouseUpButtonEvent.java
  engine/src/main/java/org/terasology/input/events/MouseButtonEvent.java
  engine/src/main/java/org/terasology/input/events/MouseDownButtonEvent.java
  engine/src/main/java/org/terasology/input/events/MouseUpButtonEvent.java
  engine/src/main/java/org/terasology/input/events/MouseWheelEvent.java
  engine/src/main/java/org/terasology/input/events/RightMouseDownButtonEvent.java
  engine/src/main/java/org/terasology/input/events/RightMouseUpButtonEvent.java
  engine/src/main/java/org/terasology/input/internal/AbstractBindableAxis.java
  engine/src/main/java/org/terasology/input/internal/BindableButtonImpl.java
  engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java
Labels: Enhancement

#4267 fix(network): fix server info request and ping error handling
  engine/src/main/java/org/terasology/network/PingService.java
  engine/src/main/java/org/terasology/network/ServerInfoService.java
Labels: Bug

#4269 Drop creation of unnecessary array on new chunk event
  engine/src/main/java/org/terasology/physics/engine/VoxelLiquidWorldSystem.java
  engine/src/main/java/org/terasology/physics/engine/VoxelWorldSystem.java
Labels: Performance

#4275 feat(JOML): migrate `AudioManager`
  engine/src/main/java/org/terasology/audio/AudioManager.java
  engine/src/main/java/org/terasology/audio/nullAudio/NullAudioManager.java
  engine/src/main/java/org/terasology/audio/openAL/OpenALManager.java
Labels: Enhancement

#4284 feat(JOML): add util for `Region3i` from `BlockRegion`
  engine/src/main/java/org/terasology/math/JomlUtil.java
Labels: Enhancement

#4278 fix: prevent NPE during movement interpolation
  engine/src/main/java/org/terasology/logic/characters/CharacterMovementSystemUtility.java
  engine/src/main/java/org/terasology/world/chunks/pipeline/PositionFuture.java
Labels: Bug

#4272 feat(BlockRegion): add BlockRegion helpers
  engine-tests/src/test/java/org/terasology/math/BlockRegionTest.java
  engine-tests/src/test/java/org/terasology/world/block/BlockRegionIterableTest.java
  engine-tests/src/test/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProviderTest.java
  engine/src/main/java/org/terasology/persistence/typeHandling/mathTypes/BlockRegionTypeHandler.java
  engine/src/main/java/org/terasology/world/block/BlockRegion.java
  engine/src/main/java/org/terasology/world/block/BlockRegionIterable.java
  engine/src/main/java/org/terasology/world/block/BlockRegions.java
  engine/src/main/java/org/terasology/world/block/regions/BlockRegionComponent.java
  engine/src/main/java/org/terasology/world/block/regions/BlockRegionSystem.java
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/LocalChunkProvider.java
  engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
  engine/src/main/java/org/terasology/world/propagation/StandardBatchPropagator.java
Labels: Enhancement, Stabilization
