Repository MovingBlocks/Terasology, pull requests merged in 2020-04, with the labels that each got.

#3885 bumped version of joml and resolved direction of lightshafts
  engine/build.gradle
  engine/src/main/java/org/terasology/rendering/dag/nodes/LightShaftsNode.java
Labels: Bug, Rendering

#3886 fix: Use 16 bit TeraArray in ChunkImpl
  engine/src/main/java/org/terasology/world/block/internal/BlockManagerImpl.java
  engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java
Labels: Bug

#3891 chore: Add JavaDoc and fix some prefabs
  engine/src/main/java/org/terasology/logic/chat/ChatMessageEvent.java
  engine/src/main/resources/assets/prefabs/floatingCube.prefab
  engine/src/main/resources/assets/prefabs/player/player.prefab
Labels: Bug, Documentation

#3893 feat: Make DebugMetrics available to modules
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugMetricsSystem.java
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/DebugOverlay.java
  engine/src/main/java/org/terasology/rendering/nui/layers/ingame/metrics/MetricsMode.java
Labels: Api

#3895 Added a double-click listener in UIText - see #3884
  engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java
Labels: UI

#3841 feat: improve 'playerHeight' command
  engine/src/main/java/org/terasology/logic/characters/CharacterMovementComponent.java
  engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
Labels: Enhancement

#3897 Comment out a bit more VR stuff to avoid a native resolution issue in module standalone workspaces
  engine/src/main/java/org/terasology/logic/players/FirstPersonHeldItemMountPointComponent.java
Labels: Logistics

#3910 feat: add retain components component
  .gitattributes
  engine/src/main/java/org/terasology/logic/common/RetainComponentsComponent.java
  engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
Labels: Enhancement

#3911 fix: Add logic check to allow visible water under other blocks
  engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
Labels: Bug

#3907 feat: Add events to scale character
  engine/src/main/java/org/terasology/logic/characters/CharacterScalingSystem.java
  engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java
  engine/src/main/java/org/terasology/logic/characters/GazeAuthoritySystem.java
  engine/src/main/java/org/terasology/logic/characters/GazeMountPointComponent.java
  engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java
  engine/src/main/java/org/terasology/logic/characters/events/OnScaleEvent.java
  engine/src/main/java/org/terasology/logic/characters/events/ScaleByRequest.java
  engine/src/main/java/org/terasology/logic/characters/events/ScaleToRequest.java
  engine/src/main/java/org/terasology/logic/debug/MovementDebugCommands.java
  engine/src/main/java/org/terasology/logic/players/LocalPlayerSystem.java
  engine/src/main/resources/assets/prefabs/player/player.prefab
Labels: Enhancement, WIP

#3912 feat(JOML): Migrate PlayerFactory
  engine/src/main/java/org/terasology/logic/location/Location.java
  engine/src/main/java/org/terasology/logic/players/PlayerFactory.java
  engine/src/main/java/org/terasology/logic/players/PlayerSystem.java
  engine/src/main/java/org/terasology/math/JomlUtil.java
  engine/src/main/java/org/terasology/math/SpiralIterable.java
Labels: Api, Enhancement

#3908 JOML migration for AudioManager
  engine/src/main/java/org/terasology/audio/AudioManager.java
  engine/src/main/java/org/terasology/audio/nullAudio/NullAudioManager.java
  engine/src/main/java/org/terasology/audio/openAL/BaseSoundSource.java
  engine/src/main/java/org/terasology/audio/openAL/OpenALManager.java
  engine/src/main/java/org/terasology/audio/openAL/SoundSource.java
Labels: Architecture

#3899 feat(JOML): Migrate methods of WorldProvider
  engine-tests/src/main/java/org/terasology/MapWorldProvider.java
  engine-tests/src/main/java/org/terasology/testUtil/WorldProviderCoreStub.java
  engine-tests/src/test/java/org/terasology/world/EntityAwareWorldProviderTest.java
  engine/src/main/java/org/terasology/world/WorldProvider.java
  engine/src/main/java/org/terasology/world/internal/AbstractWorldProviderDecorator.java
  engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
  engine/src/main/java/org/terasology/world/internal/WorldProviderCore.java
  engine/src/main/java/org/terasology/world/internal/WorldProviderCoreImpl.java
  engine/src/main/java/org/terasology/world/internal/WorldProviderWrapper.java
Labels: Api, Enhancement
