Repository MovingBlocks/Terasology, pull requests merged in 2021-06, with the labels that each got.

#4729 rendering: migrate sky sphere
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseRemoteWorld.java
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseWorld.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/SphereBuilder.java
  engine/src/main/java/org/terasology/engine/rendering/backdrop/BackdropRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/backdrop/Skysphere.java
  engine/src/main/resources/org/terasology/engine/assets/shaders/sky_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/sky_vert.glsl
  facades/TeraEd/src/main/java/org/terasology/editor/properties/SceneProperties.java
Labels: Topic: Rendering, Type: Refactoring

#4726 fix: adjust 'Land.ogg' sound asset to be mono channel
  engine/src/main/resources/org/terasology/engine/assets/sounds/Land.ogg
Labels: Topic: UI/UX, Type: Bug

#4738 chore: mark stateChange as deprecated with changes to camera
  engine/src/main/java/org/terasology/engine/rendering/dag/stateChanges/LookThroughDefault.java
  engine/src/main/java/org/terasology/engine/rendering/dag/stateChanges/LookThroughNormalized.java
Labels: Type: Chore

#4737 chore(rendering): remove bindings from ShaderManager
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/renderer/ShaderManagerHeadless.java
  engine/src/main/java/org/terasology/engine/rendering/ShaderManager.java
  engine/src/main/java/org/terasology/engine/rendering/ShaderManagerLwjgl.java
Labels: Topic: Rendering, Type: Chore

#4741 chore: change entity dump filename to '<timestamp>-entityDump.json'
  .gitignore
  engine/src/main/java/org/terasology/engine/logic/console/commands/CoreCommands.java
Labels: Topic: Stabilization, Type: Chore

#4634 feature(rendering)!: add vertex attribute scheme
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/assets/HeadlessMesh.java
  engine/src/main/java/org/terasology/engine/monitoring/chunk/ChunkMeshInfo.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/ChunkMeshTypeHandler.java
  engine/src/main/java/org/terasology/engine/physics/bullet/BulletPhysics.java
  engine/src/main/java/org/terasology/engine/rendering/AABBRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/Mesh.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/MeshBuilder.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/MeshData.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/ObjMeshFormat.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/ScreenQuadMeshProducer.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/SphereBuilder.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/StandardMeshData.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/layout/ByteLayout.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/layout/DoubleLayout.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/layout/FloatLayout.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/layout/IntLayout.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/layout/Layout.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/layout/ShortLayout.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/BaseVertexAttribute.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/BufferedResource.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/DrawingMode.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/GLAttributes.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/IndexResource.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/TypeMapping.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexAttribute.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexAttributeBinding.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexBinding.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexFloatAttribute.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexFloatAttributeBinding.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexIntegerAttribute.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexIntegerAttributeBinding.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexResource.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexResourceBuilder.java
  engine/src/main/java/org/terasology/engine/rendering/assets/skeletalmesh/SkeletalMeshDataBuilder.java
  engine/src/main/java/org/terasology/engine/rendering/gltf/GLTFAttributeMapping.java
  engine/src/main/java/org/terasology/engine/rendering/gltf/GLTFMeshFormat.java
  engine/src/main/java/org/terasology/engine/rendering/gltf/MeshAttributeSemantic.java
  engine/src/main/java/org/terasology/engine/rendering/iconmesh/IconMeshFactory.java
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/LwjglCanvasRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMesh.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMeshBase.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMesh.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkTessellator.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/Tessellator.java
  engine/src/main/java/org/terasology/engine/world/block/shapes/BlockMeshPart.java
  engine/src/main/resources/org/terasology/engine/assets/shaders/chunk_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/chunk_vert.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/shadowMap_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/shadowMap_vert.glsl
  engine/src/main/resources/org/terasology/engine/include/globalFunctionsFragIncl.glsl
  engine/src/main/resources/org/terasology/engine/include/globalFunctionsVertIncl.glsl
Labels: Breaking Change, Topic: Architecture, Type: Improvement

#4730 chore: migrate light deferred shader and cleanup usage of Sphere
  engine/src/main/java/org/terasology/engine/rendering/backdrop/Skysphere.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/Sphere.java
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_vert.glsl
Labels: Topic: Rendering, Type: Chore, Type: Refactoring

#4744 fix: correct extra indices sphere builder
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/SphereBuilder.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/IndexResource.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMesh.java
Labels: Category: Build/CI, Topic: Rendering, Type: Bug

#4745 fix: resolve lightgeometry pass problems with nonfunctional point lights
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_vert.glsl
Labels: Type: Bug

#4746 chore(rendering): remove refrences to immediate mode
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/renderer/NullCamera.java
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglDisplayDevice.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/Camera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/OpenVRStereoCamera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/OrthographicCamera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/PerspectiveCamera.java
  engine/src/main/java/org/terasology/engine/rendering/dag/stateChanges/LookThrough.java
  engine/src/main/java/org/terasology/engine/rendering/dag/stateChanges/LookThroughDefault.java
  engine/src/main/java/org/terasology/engine/rendering/dag/stateChanges/LookThroughNormalized.java
Labels: Type: Chore

#4728 doc: improve document of PlaySound and PlaySoundForOwner events
  engine/src/main/java/org/terasology/engine/audio/events/PlaySoundEvent.java
  engine/src/main/java/org/terasology/engine/audio/events/PlaySoundForOwnerEvent.java
Labels: Category: Doc

#4739 chore(rendering): remove OpenGLUtils
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLUtils.java
Labels: Topic: Rendering, Type: Chore

#4711 bugfix: set core profile to 3.3
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglGraphics.java
Labels: Topic: Rendering

#4748 chore: consume TeraNUI v3 release
  engine/build.gradle
  subsystems/TypeHandlerLibrary/build.gradle.kts
Labels: Blocker, Category: Build/CI, Type: Chore

#4751 fix: world generation with zones
  engine/src/main/java/org/terasology/engine/world/generation/WorldBuilder.java
Labels: Topic: WorldGen, Type: Bug

#4750 chore(rendering): remove usage of GL_ARB_framebuffer and reworked shadowmap and lightpass
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglGraphicsUtil.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java
  engine/src/main/resources/default.cfg
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/shadowMap_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/shadowMap_vert.glsl
  engine/src/main/resources/org/terasology/engine/include/globalFunctionsFragIncl.glsl
Labels: Topic: Rendering, Type: Chore

#4670 chore: replace map with switch cases for Side
  engine/src/main/java/org/terasology/engine/math/Side.java
Labels: Type: Chore

#4752 fix: lightgeometrypass to allow shadows to be disabled
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightGeometryPass_frag.glsl
Labels: Type: Bug

#4754 doc: update minimal system requirements for OpenGL 3.3
  README.markdown
Labels: Category: Doc

#4755 feature: migrate RegionOutlineRenderer and allow support to specify AllocationType
  engine/src/main/java/org/terasology/engine/rendering/AABBRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/MeshData.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/StandardMeshData.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/AllocationType.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/BufferedResource.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/IndexResource.java
  engine/src/main/java/org/terasology/engine/rendering/logic/RegionOutlineRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMesh.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMeshBase.java
Labels: Topic: Rendering, Type: Improvement

#4740 fix: prevent NPE with DelayManager on remote clients
  subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCSystem.java
Labels: Blocker, Category: Crash, Topic: Stabilization, Type: Bug

#4749 build(Jenkinsfile): improve pipeline performance; add docstrings
  Jenkinsfile
  build.gradle
Labels: Category: Build/CI, Category: Doc

#4747 chore(ModuleManager): refactor and document engine module setup
  engine-tests/src/test/java/org/terasology/engine/core/module/ModuleManagerTest.java
  engine-tests/src/test/java/org/terasology/engine/persistence/typeHandling/reflection/TestModuleEnvironmentSandbox.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
Labels: Type: Chore

#4761 chore: upgrade to gestalt 7.1.0 from snapshot
  build-logic/build.gradle.kts
  engine/build.gradle
  subsystems/TypeHandlerLibrary/build.gradle.kts
Labels: Blocker, Type: Chore

#4763 chore: remove check for Opengl33
  engine/src/main/java/org/terasology/engine/rendering/ShaderManagerLwjgl.java
Labels: Type: Chore

#4756 chore: replace getAllSides with values()
  engine-tests/src/test/java/org/terasology/math/RotationTest.java
  engine-tests/src/test/java/org/terasology/math/SideTest.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/BlockMeshGeneratorSingleShape.java
  engine/src/main/java/org/terasology/engine/world/block/entity/neighbourUpdate/NeighbourBlockFamilyUpdateSystem.java
  engine/src/main/java/org/terasology/engine/world/block/family/AttachedToSurfaceFamily.java
  engine/src/main/java/org/terasology/engine/world/block/internal/BlockBuilder.java
  engine/src/main/java/org/terasology/engine/world/block/shapes/BlockShapeImpl.java
  engine/src/main/java/org/terasology/engine/world/block/structure/AttachSupportRequired.java
  engine/src/main/java/org/terasology/engine/world/block/structure/BlockStructuralSupportSystem.java
  engine/src/main/java/org/terasology/engine/world/propagation/StandardBatchPropagator.java
  engine/src/main/java/org/terasology/engine/world/propagation/light/LightMerger.java
Labels: Type: Chore

#4764 build: update TeraConfig to 1.6.3 and adjust IntelliJ settings
  .idea/codeStyles/Project.xml
  build.gradle
Labels: Category: Build/CI, Category: Test/QA, Type: Chore

#4767 bugfix(rendering): rework glsl for osx
  engine/src/main/java/org/terasology/engine/rendering/assets/font/FontMaterialProducer.java
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/LwjglCanvasRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/TerasologyCanvasImpl.java
  engine/src/main/java/org/terasology/engine/rendering/world/selection/BlockSelectionRenderer.java
  engine/src/main/resources/org/terasology/engine/assets/materials/ui/UIUnderline.mat
  engine/src/main/resources/org/terasology/engine/assets/shaders/blockSelection.info
  engine/src/main/resources/org/terasology/engine/assets/shaders/blockSelection_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/block_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/debug_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/debug_vert.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/defaultTextured.info
  engine/src/main/resources/org/terasology/engine/assets/shaders/default_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/genericMeshMaterial_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/particle_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/particle_geom.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/particle_vert.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/simple_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/simple_vert.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/ui/font.info
  engine/src/main/resources/org/terasology/engine/assets/shaders/ui/font_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/ui/uiLitMesh.info
  engine/src/main/resources/org/terasology/engine/assets/shaders/ui/uiLitMesh_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/ui/uitexture.info
  engine/src/main/resources/org/terasology/engine/assets/shaders/ui/uitexture_frag.glsl
Labels: Topic: Rendering, Type: Bug

#4766 fix(rendering): remove unsupported ARB for opengl 2.0
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLShader.java
Labels: Topic: Rendering, Type: Bug

#4762 chore: reusue Floatbuffer for uniform
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLMaterial.java
Labels: Topic: Rendering, Type: Chore

#4760 chore(rendering): migrate use of ARB bind framebuffer EXT and reworked readBackPixels
  engine/src/main/java/org/terasology/engine/rendering/opengl/PBO.java
Labels: Topic: Rendering, Type: Chore

#4771 chore: minor cleanup for ChunkProcessingPipeline
  engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
Labels: Topic: WorldGen, Type: Chore

#4662 chore: remove finite check from LocalPlayer
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayer.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/DebugOverlay.java
Labels: Type: Chore

#4772 chore: cache hashcode for uniform id
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLMaterial.java
Labels: Type: Chore

#4776 refactor(bootstrap): remove duplicate registerComponents method
  engine/src/main/java/org/terasology/engine/core/bootstrap/EntitySystemSetupUtil.java
  engine/src/main/java/org/terasology/engine/core/bootstrap/EnvironmentSwitchHandler.java
Labels: Size: S, Type: Refactoring

#4779 fix(audio): skip update when player is invalid
  engine/src/main/java/org/terasology/engine/audio/system/AudioSystem.java
Labels: Type: Bug

#4782 feat: expose scale for BrownianNoise
  engine/src/main/java/org/terasology/engine/utilities/procedural/BrownianNoise.java
Labels: Type: Chore

#4787 fix: use link to new Jenkins in readme
  README.markdown
Labels: Category: Doc, Type: Bug

#4784 refactor: convert Jenkinsfile to declarative pipeline syntax
  Jenkinsfile
Labels: Category: Build/CI, Type: Refactoring

#4791 fix(ci): backslash-escape multi-line shell command
  Jenkinsfile
Labels: Category: Build/CI, Type: Bug

#4788 Revert "chore: remove finite check from LocalPlayer"
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayer.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/DebugOverlay.java
Labels: Blocker, Category: Crash, Type: Bug, Type: Chore

#4789 chore: empty default implementation for RenderSystem interface
  engine/src/main/java/org/terasology/engine/entitySystem/systems/RenderSystem.java
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/engine/particles/rendering/SpriteParticleRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/logic/FloatingTextRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/logic/MeshRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/logic/RegionOutlineRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/logic/SkeletonRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/world/selection/BlockSelectionRenderSystem.java
Labels: Topic: Rendering, Type: Chore

#4796 test: provide a subsystem to register the unittest module
  engine-tests/src/main/java/org/terasology/engine/testUtil/WithUnittestModule.java
Labels: Category: Test/QA

#4777 chore: remove DynamicPriorityBlockingQueue
  engine/src/main/java/org/terasology/engine/rendering/world/ChunkMeshUpdateManager.java
  engine/src/main/java/org/terasology/engine/utilities/concurrency/DynamicPriorityBlockingQueue.java
  engine/src/main/java/org/terasology/engine/utilities/concurrency/TaskMaster.java
Labels: Type: Chore

#4793 chore: minor cleanup Block
  engine/src/main/java/org/terasology/engine/world/block/Block.java
Labels: Type: Chore

#4797 fix: make BlockArea.iterator() use the same order as noise and facet data
  engine-tests/src/test/java/org/terasology/engine/world/block/BlockAreaTest.java
  engine/src/main/java/org/terasology/engine/world/block/BlockArea.java
Labels: Type: Bug
