Repository MovingBlocks/Terasology, pull requests merged in 2021-03, with the labels that each got.

#4552 fix(ConstructorLibrary): prevent AccessControlException by using `AccessController.doPrivilaged`
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/reflection/reflect/ConstructorLibrary.java
Labels: Bug

#4527 chore: replace FrustrumPlane with plane from joml-ext
  engine/src/main/java/org/terasology/rendering/cameras/FrustumPlane.java
  engine/src/main/java/org/terasology/rendering/cameras/ViewFrustum.java
Labels: Rendering, Stabilization

#4553 build: move `buildSrc` to `build-logic`
  build-logic/.gitignore
  build-logic/build.gradle.kts
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/facade.gradle.kts
  build-logic/src/main/kotlin/org/terasology/gradology/ModuleInfoException.kt
  build-logic/src/main/kotlin/org/terasology/gradology/attributes.kt
  build-logic/src/main/kotlin/org/terasology/gradology/constants.kt
  build-logic/src/main/kotlin/org/terasology/gradology/exec.kt
  build-logic/src/main/kotlin/org/terasology/gradology/module_build.kt
  build-logic/src/main/kotlin/org/terasology/gradology/module_deps.kt
  build-logic/src/main/kotlin/terasology-dist.gradle.kts
  build-logic/src/main/kotlin/terasology-module.gradle.kts
  build-logic/src/main/kotlin/terasology-repositories.gradle.kts
  build.gradle
  facades/PC/build.gradle.kts
  modules/build.gradle.kts
  settings.gradle
Labels: Logistics

#4546 feat(logs): improve prefab deserialization logging
  engine/src/main/java/org/terasology/entitySystem/prefab/internal/PrefabFormat.java
  engine/src/main/java/org/terasology/persistence/serializers/PrefabSerializer.java
Labels: Enhancement

#4554 ci: buildSrc moved to build-logic
  Jenkinsfile
Labels: Blocker, Logistics

#4528 chore!: limit API for BlockComponent (1/2)
  engine/src/main/java/org/terasology/logic/health/EntityDestructionAuthoritySystem.java
  engine/src/main/java/org/terasology/world/block/BlockComponent.java
  engine/src/main/java/org/terasology/world/block/entity/BlockEntitySystem.java
  engine/src/main/java/org/terasology/world/internal/EntityAwareWorldProvider.java
Labels: Stabilization

#4271 feat(discord-rpc): improve the system
  .idea/.gitignore
  facades/PC/src/main/resources/logback.xml
  subsystems/DiscordRPC/src/main/java/org/terasology/engine/subsystem/discordrpc/DiscordRPCBuffer.java
  subsystems/DiscordRPC/src/main/java/org/terasology/engine/subsystem/discordrpc/DiscordRPCSubSystem.java
  subsystems/DiscordRPC/src/main/java/org/terasology/engine/subsystem/discordrpc/DiscordRPCSystem.java
  subsystems/DiscordRPC/src/main/java/org/terasology/engine/subsystem/discordrpc/DiscordRPCThread.java
Labels: Enhancement

#4561 chore!: limit API for BlockComponent (2/2)
  engine/src/main/java/org/terasology/world/block/BlockComponent.java
Labels: Stabilization

#4563 chore!: remove JUnit 4 from module dependencies
  build-logic/src/main/kotlin/terasology-module.gradle.kts
Labels: Stabilization

#4567 feat: Reduce the amount of gaps that appear while LOD chunks load
  engine/src/main/java/org/terasology/rendering/world/RenderableWorldImpl.java
  engine/src/main/java/org/terasology/world/chunks/LodChunk.java
  engine/src/main/java/org/terasology/world/chunks/LodChunkProvider.java
Labels: Enhancement

#4572 test: initialize Bullet for [Headless]Environment
  engine-tests/src/main/java/org/terasology/Environment.java
Labels: Stabilization

#4577 fix: trigger update for location component for physics update
  engine/src/main/java/org/terasology/physics/bullet/BulletPhysics.java
  engine/src/main/java/org/terasology/physics/engine/PhysicsSystem.java
Labels: Bug

#4579 test(modules): set default test case timeout to four minutes
  build-logic/src/main/kotlin/terasology-module.gradle.kts
Labels: Stabilization

#4581 ModuleManager: ensure engine module is always present in environment
  engine/src/main/java/org/terasology/engine/module/ModuleManager.java
Labels: Blocker, Bug

#4588 fix(PathManager): avoid calling Files method on paths that may not exist yet
  engine/src/main/java/org/terasology/engine/core/paths/PathManager.java
Labels: Blocker, Bug

#4589 refactor: restore generated files to their generated location
  engine/src/main/java/org/terasology/protobuf/EntityData.java
  engine/src/main/java/org/terasology/protobuf/NetData.java
  engine/src/main/java/org/terasology/protobuf/package-info.java
Labels: Blocker

#4590 Don't move the camera when window is refocused
  engine/src/main/java/org/terasology/engine/input/lwjgl/LwjglMouseDevice.java
Labels: Bug
