Repository MovingBlocks/Terasology, pull requests merged in 2021-02, with the labels that each got.

#4347 build(facades.PC): tidy distribution tasks
  .gitignore
  .idea/copyright/profiles_settings.xml
  Jenkinsfile
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/terasology-dist.gradle.kts
  engine/build.gradle
  facades/PC/build.gradle.kts
  facades/PC/launchScripts/TeraEd.exe
  facades/PC/launchScripts/Terasology.x64.exe
  facades/PC/launchScripts/Terasology.x86.exe
  facades/PC/launchScripts/run_linux.sh
  facades/PC/launchScripts/run_macosx.command
  facades/PC/launchScriptsSrc/LauncherTeraEd.xml
  facades/PC/launchScriptsSrc/README.MD
  facades/PC/src/main/startScripts/unixStartScript.gsp
  facades/PC/src/main/startScripts/windowsStartScript.bat.gsp
  gradle/wrapper/gradle-wrapper.properties
Labels: Logistics

#4439 upgrade gradle to 6.8.1
  engine-tests/src/test/java/org/terasology/math/RotationTest.java
  engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java
Labels: Logistics

#4454 build(PC): move modules back off the classpath so the sandbox works
  .gitignore
  .idea/.editorconfig
  .idea/runConfigurations/TeraEd__rendering_editor_.xml
  .idea/runConfigurations/TerasologyPC.xml
  .idea/runConfigurations/TerasologyPC__2nd_client_.xml
  .idea/runConfigurations/TerasologyPC__2nd_client_for_mac.xml
  .idea/runConfigurations/TerasologyPC__3rd_client_.xml
  .idea/runConfigurations/TerasologyPC__CR_enabled_.xml
  .idea/runConfigurations/TerasologyPC__EXTREME_8GB_.xml
  .idea/runConfigurations/TerasologyPC__Headless_.xml
  .idea/runConfigurations/TerasologyPC__Java_FlightRecorder_.xml
  .idea/runConfigurations/TerasologyPC__Splash_disabled_.xml
  .idea/runConfigurations/TerasologyPC__load_latest_.xml
  .idea/runConfigurations/TerasologyPC__no_audio_.xml
  .idea/runConfigurations/TerasologyPC__no_saves_.xml
  .idea/runConfigurations/TerasologyPC__permissive_security_.xml
  .idea/runConfigurations/TerasologyPC__recreate_latest_.xml
  .idea/runConfigurations/TerasologyPC_for_mac.xml
  .idea/runConfigurations/engine_tests_with_JaCoCo.xml
  buildSrc/src/main/kotlin/facade.gradle.kts
  buildSrc/src/main/kotlin/org/terasology/gradology/attributes.kt
  buildSrc/src/main/kotlin/org/terasology/gradology/exec.kt
  buildSrc/src/main/kotlin/org/terasology/gradology/module_deps.kt
  buildSrc/src/main/kotlin/terasology-module.gradle.kts
  buildSrc/src/main/kotlin/terasology-repositories.gradle.kts
  config/gradle/common.gradle
  engine/src/main/java/org/terasology/engine/paths/PathManager.java
  facades/PC/build.gradle.kts
  modules/build.gradle.kts
Labels: Logistics

#4465 build: patch upgrade to gradle 6.8.2
  gradle/wrapper/gradle-wrapper.properties
Labels: Logistics

#4467 build(PC): add gradle command-line option for max heap size
  buildSrc/src/main/kotlin/org/terasology/gradology/exec.kt
Labels: Logistics

#4466 fix(ModuleManager): fix improperly-escaped spaces in module path
  engine-tests/src/test/java/org/terasology/engine/module/ModuleManagerTest.java
  engine-tests/src/test/resources/org/terasology/engine/module/messy-name-directory & $t#f/testmessy-1.0.0-SNAPSHOT.jar
  engine-tests/src/test/resources/org/terasology/engine/module/testdummy-1.0.0-SNAPSHOT.jar
  engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
Labels: Bug

#4410 doc: add conventional commits to contributing guidelines
  .github/CONTRIBUTING.md
Labels: Documentation, Research

#4472 perf: avoid string operations when validating visible blocks
  engine/src/main/java/org/terasology/rendering/primitives/BlockMeshGeneratorSingleShape.java
Labels: Performance

#4438 perf(chunk-sparse-array): replace dense arrays to sparse arrays for lightdata
  engine/src/main/java/org/terasology/world/chunks/internal/ChunkImpl.java
Labels: Performance

#4471 perf(GL): move opengl33 off of draw loop
  engine/src/main/java/org/terasology/particles/rendering/SpriteParticleRenderer.java
Labels: Performance, Rendering

#4507 CI: fix path to versionInfo.properties
  Jenkinsfile
Labels: Blocker, Logistics

#4512 chore(behavior,logic): minor code cleanup
  engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java
  engine/src/main/java/org/terasology/logic/behavior/CollectiveBehaviorSystem.java
  engine/src/main/java/org/terasology/logic/nameTags/PlayerNameTagSystem.java
Labels: Stabilization

#4518 fix: correct index for world view
  engine/src/main/java/org/terasology/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
Labels: Bug

#4516 feat(block): Add 'Blocks' utility class to convert world to block coordinates
  engine-tests/src/test/java/org/terasology/world/block/BlocksTest.java
  engine/src/main/java/org/terasology/world/block/Blocks.java
Labels: Api, Stabilization

#4514 build: factor out methods making gradle dependencies from gestalt metadata
  buildSrc/src/main/kotlin/org/terasology/gradology/constants.kt
  buildSrc/src/main/kotlin/org/terasology/gradology/module_build.kt
  buildSrc/src/main/kotlin/org/terasology/gradology/module_deps.kt
  buildSrc/src/main/kotlin/terasology-module.gradle.kts
Labels: Logistics

#4511 build: factor out ModuleInfoException from terasology-module
  buildSrc/src/main/kotlin/org/terasology/gradology/ModuleInfoException.kt
  buildSrc/src/main/kotlin/terasology-module.gradle.kts
Labels: Logistics

#4479 fix(ModuleManger): let loadModulesFromClassPaths load source modules
  engine-tests/src/main/java/org/terasology/entitySystem/stubs/StringComponent.java
  engine-tests/src/main/java/org/terasology/testUtil/ModuleManagerFactory.java
  engine-tests/src/test/java/org/terasology/engine/module/ClasspathSupportingModuleLoaderTest.java
  engine-tests/src/test/java/org/terasology/engine/module/ModuleManagerTest.java
  engine-tests/src/test/resources/org/terasology/engine/module/Spacey Parent/SourceModuleFixture/module.txt
  engine/src/main/java/org/terasology/engine/module/APIScannerTolerantOfAssetOnlyModules.java
  engine/src/main/java/org/terasology/engine/module/ClasspathSupportingModuleLoader.java
  engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
  engine/src/main/java/org/terasology/entitySystem/entity/EntityBuilder.java
  engine/src/main/java/org/terasology/utilities/Jvm.java
Labels: Blocker

#4529 fix: use system property instead of ENV to determine user home
  engine/src/main/java/org/terasology/utilities/Jvm.java
Labels: Blocker, Bug, Stabilization

#4463 build(PC): remove unused tasks for running headless server from source
  facades/PC/build.gradle.kts
  facades/PC/server.build.gradle
Labels: Logistics

#4533 chore: Updated default ports, server for logstash
  engine/src/main/java/org/terasology/telemetry/logstash/TelemetryLogstashAppender.java
Labels: Logistics

#4522 build: move more implementation details about gestalt out of terasology-module
  buildSrc/src/main/kotlin/org/terasology/gradology/constants.kt
  buildSrc/src/main/kotlin/org/terasology/gradology/module_build.kt
  buildSrc/src/main/kotlin/terasology-module.gradle.kts
Labels: Logistics

#4539 refactor(ModuleManager): replace interface with concrete class
  engine-tests/src/main/java/org/terasology/testUtil/ModuleManagerFactory.java
  engine/src/main/java/org/terasology/engine/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/module/ModuleManager.java
  engine/src/main/java/org/terasology/engine/module/ModuleManagerImpl.java
Labels: Stabilization

#4540 refactor(ModuleManager): factor initiliaztion code to multiple methods
  engine/src/main/java/org/terasology/engine/module/ModuleManager.java
Labels: Stabilization

#4244 feat: Reviving of "UI for editing arbitrary types and AutoConfigs"
  engine-tests/src/main/java/org/terasology/config/flexible/TestAutoConfig.java
  engine-tests/src/test/java/org/terasology/config/flexible/AutoConfigTest.java
  engine-tests/src/test/java/org/terasology/config/flexible/ui/SettingWidgetFactoryTest.java
  engine-tests/src/test/java/org/terasology/persistence/serializers/TypeSerializerTest.java
  engine-tests/src/test/java/org/terasology/persistence/serializers/VectorTypeSerializerTest.java
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/mathTypes/BlockAreaTypeHandlerTest.java
  engine-tests/src/test/java/org/terasology/reflection/reflect/ConstructorLibraryTest.java
  engine-tests/src/test/java/org/terasology/utilities/ReflectionUtilTest.java
  engine/build.gradle
  engine/src/main/java/org/terasology/config/AudioConfig.java
  engine/src/main/java/org/terasology/config/flexible/AutoConfig.java
  engine/src/main/java/org/terasology/config/flexible/AutoConfigManager.java
  engine/src/main/java/org/terasology/config/flexible/ui/AssetBackedConstraintWidgetFactory.java
  engine/src/main/java/org/terasology/config/flexible/ui/AutoConfigScreen.java
  engine/src/main/java/org/terasology/config/flexible/ui/AutoConfigWidgetFactory.java
  engine/src/main/java/org/terasology/config/flexible/ui/ConstraintWidgetFactory.java
  engine/src/main/java/org/terasology/config/flexible/ui/NumberRangeConstraintWidgetFactory.java
  engine/src/main/java/org/terasology/config/flexible/ui/SettingWidgetFactory.java
  engine/src/main/java/org/terasology/engine/module/ModuleContext.java
  engine/src/main/java/org/terasology/engine/module/ModuleManager.java
  engine/src/main/java/org/terasology/persistence/internal/GlobalStoreLoader.java
  engine/src/main/java/org/terasology/persistence/serializers/PrefabSerializer.java
  engine/src/main/java/org/terasology/persistence/serializers/WorldSerializerImpl.java
  engine/src/main/java/org/terasology/persistence/typeHandling/reflection/ModuleEnvironmentSandbox.java
  engine/src/main/java/org/terasology/physics/CollisionGroupManager.java
  engine/src/main/java/org/terasology/rendering/nui/asset/UIFormat.java
  engine/src/main/java/org/terasology/rendering/nui/editor/utils/NUIEditorNodeUtils.java
  engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java
  engine/src/main/java/org/terasology/rendering/nui/internal/TypeWidgetLibraryImpl.java
  engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/settings/SettingsMenuScreen.java
  engine/src/main/java/org/terasology/rendering/nui/layouts/RowLayout.java
  engine/src/main/java/org/terasology/rendering/nui/skin/UISkinFormat.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/TypeWidgetFactoryRegistryImpl.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/testScreens/BuiltinTypeWidgetTestScreen.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/testScreens/MathTypeWidgetTestScreen.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/testScreens/TypeWidgetTestScreen.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/types/ArrayWidgetFactory.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/types/CollectionWidgetFactory.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/types/CollisionGroupWidgetFactory.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/types/EnumWidgetFactory.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/types/object/ObjectLayoutBuilder.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/types/object/ObjectWidgetFactory.java
  engine/src/main/java/org/terasology/rendering/nui/widgets/types/object/SubtypeLayoutBuilder.java
  engine/src/main/java/org/terasology/utilities/ReflectionUtil.java
  engine/src/main/java/org/terasology/utilities/collection/ImmutableCollectionUtil.java
  engine/src/main/resources/assets/ui/config/autoConfigScreen.ui
  engine/src/main/resources/assets/ui/config/numberRangeSettingWidget.ui
  engine/src/main/resources/assets/ui/menu/settingsMenuScreen.ui
  engine/src/main/resources/assets/ui/types/builtinTypeWidgetTestScreen.ui
  engine/src/main/resources/assets/ui/types/mathTypeWidgetTestScreen.ui
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/CollectionTypeHandler.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/factories/CollectionTypeHandlerFactory.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/reflection/reflect/CollectionCopyConstructor.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/reflection/reflect/ConstructorLibrary.java
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/CollectionTypeHandlerTest.java
Labels: Architecture, Enhancement, UI

#4541 fix: correct matrix calculation for compound shapes (#4403)
  engine/src/main/java/org/terasology/physics/bullet/shapes/BulletCompoundShape.java
Labels: Bug

#4548 chore: adding some null checks
  engine/src/main/java/org/terasology/engine/bootstrap/EntitySystemSetupUtil.java
  engine/src/main/java/org/terasology/engine/bootstrap/EnvironmentSwitchHandler.java
  engine/src/main/java/org/terasology/world/generator/internal/WorldGeneratorManager.java
Labels: Stabilization
