Repository MovingBlocks/Terasology, pull requests merged in 2021-11, with the labels that each got.

#4937 fix(SystemConfig): ensure thread max limit is never less than one
  engine/src/main/java/org/terasology/engine/config/SystemConfig.java
Labels: Type: Bug

#4896 refactor: refactor mesh generation for IconMeshFactory
  engine/src/main/java/org/terasology/engine/rendering/iconmesh/IconMeshFactory.java
Labels: Type: Refactoring

#4939 chore: add reactor-extra to dependencies
  engine/build.gradle
Labels: Category: Build/CI, Size: S, Type: Chore, Topic: Concurrency

#4927 build(ci): build using a java 11 toolchain
  Jenkinsfile
Labels: Category: Build/CI

#4941 Revert "build(ci): build using a java 11 toolchain"
  Jenkinsfile
Labels: Category: Build/CI

#4940 test: add unitTest target to TypeHandlerLibrary and facades
  build-logic/src/main/kotlin/facade.gradle.kts
  subsystems/TypeHandlerLibrary/build.gradle.kts
Labels: Type: Bug, Category: Build/CI, Category: Test/QA, Size: S

#4944 test(TypeHandlerLibrary): provide a logger during test execution
  subsystems/TypeHandlerLibrary/build.gradle.kts
Labels: Type: Bug, Category: Test/QA, Size: S

#3992 test(TypeHandlerLibrary): RuntimeDelegatingTypeHandler test failure
  .idea/dictionaries/kevint.xml
  .idea/inspectionProfiles/Terasology.xml
  subsystems/TypeHandlerLibrary/build.gradle.kts
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/RuntimeDelegatingTypeHandlerTest.java
Labels: Blocker, Category: Test/QA

#4942 build: build using a java 11 toolchain
  Jenkinsfile
Labels: Category: Build/CI

#4928 build: upgrade minimum compatible version to Java 11
  build.gradle
  config/gradle/common.gradle
Labels: Category: Build/CI

#4932 fix(engine/rendering): Fix ChunkMeshRenderer listens to wrong deactivate event
  engine/src/main/java/org/terasology/engine/rendering/logic/ChunkMeshRenderer.java
Labels: Type: Bug, Topic: Rendering

#4945 build: fix mystery Artifactory issue
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/terasology-repositories.gradle.kts
  build.gradle
  templates/build.gradle
Labels: Category: Build/CI, Blocker

#4893 refactor: split chunkMesh to ChunkMeshImpl
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/ChunkMeshTypeHandler.java
  engine/src/main/java/org/terasology/engine/rendering/logic/ChunkMeshRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/DebugOverlay.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMesh.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMeshImpl.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkTessellator.java
  engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java
  engine/src/main/java/org/terasology/engine/world/chunks/LodChunkProvider.java
Labels: Type: Chore, Type: Refactoring

#4897 fix(rendering): replicate SkeletalMesh fields, fix debug skeleton scale
  engine/src/main/java/org/terasology/engine/rendering/logic/SkeletalMeshComponent.java
  engine/src/main/java/org/terasology/engine/rendering/logic/SkeletonRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLSkeletalMesh.java
Labels: Type: Bug, Topic: Rendering

#4946 feat(F3): show process data size and limit
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/DebugOverlay.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/MetricsMode.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/NetworkStatsMode.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/NullMetricsMode.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/RunningThreadsMode.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/WorldRendererMode.java
  engine/src/main/java/org/terasology/engine/utilities/OperatingSystemMemory.java
Labels: Category: Performance, Type: Improvement, Category: Test/QA, Size: S

#4938 build(javadoc): disable doclint messages about missing tags
  config/gradle/common.gradle
Labels: Category: Doc, Category: Build/CI, Size: S

#4936 chore: remove some slow logging
  engine/src/main/java/org/terasology/engine/network/internal/NetworkSystemImpl.java
Labels: Category: Performance, Type: Chore

#4954 chore: overhaul issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/crash-bug-report.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
  .github/ISSUE_TEMPLATE/roadmap-draft.md
Labels: Category: Doc, Status: Needs Discussion, Type: Chore

#4899 ci: fail checkstyle on all findings except warning.LOW
  Jenkinsfile
  engine-tests/src/main/java/org/terasology/unittest/stubs/StringComponent.java
  engine/src/main/java/org/terasology/engine/entitySystem/systems/RenderSystem.java
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/LineRenderer.java
  engine/src/main/java/org/terasology/engine/world/propagation/light/LightMerger.java
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
  facades/PC/src/test/java/org/terasology/engine/DataSizeConverterTest.java
Labels: Category: Build/CI, Category: Test/QA, Size: S, Type: Chore

#4894 refactor: construct block mesh generator single shape with standard mesh data
  engine/src/main/java/org/terasology/engine/rendering/primitives/BlockMeshGeneratorSingleShape.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/BlockMeshShapeGenerator.java
Labels: Type: Chore, Type: Refactoring

#4962 fix(headless-execution): MainMenuState can handle headless now. Correct loadingstate for headless clients.
  engine/src/main/java/org/terasology/engine/core/modes/StateLoading.java
  engine/src/main/java/org/terasology/engine/core/modes/StateMainMenu.java
Labels: Type: Bug

#4935 feat(i18n): Update engine settings i18n
  engine/src/main/java/org/terasology/engine/config/SystemConfig.java
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_en.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_uk.lang
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/playerMenuScreen.ui
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/settingsMenuScreen.ui
Labels: Topic: UI/UX
