Repository MovingBlocks/Terasology, pull requests merged in 2021-10, with the labels that each got.

#4918 chore(StateMainMenu): include message in toString representation for debugging
  engine/src/main/java/org/terasology/engine/core/modes/StateMainMenu.java
Labels: Size: S, Type: Chore

#4919 fix: Avoid a couple cases where no NUIManager would cause trouble.
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/StartServer.java
  engine/src/main/java/org/terasology/engine/network/internal/NetworkSystemImpl.java
  engine/src/main/java/org/terasology/engine/rendering/nui/skin/UISkinFormat.java
Labels: Type: Bug, Multiplayer, Blocker, Category: Crash

#4905 refactor: add test cases for vertex resource and update api with put and replace
  engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexResourceTest.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/ChunkMeshTypeHandler.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/StandardMeshData.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/BufferedResource.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/IndexResource.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexResource.java
Labels: Type: Refactoring

#4795 chore: remove finite check from LocalPlayer
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayer.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/DebugOverlay.java
  engine/src/main/java/org/terasology/engine/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
Labels: Type: Chore

#4934 feat(i18n): Update Ukrainian locale with current strings
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_uk.lang
Labels: Topic: UI/UX

#4931 refactor(translation): use `ResourceUrn` instead of `SimpleUrn`
  engine-tests/src/test/java/org/terasology/i18n/TranslationFormatTests.java
  engine/src/main/java/org/terasology/engine/config/flexible/ui/LocaleConstraintWidgetFactory.java
  engine/src/main/java/org/terasology/engine/i18n/TranslationSystem.java
  engine/src/main/java/org/terasology/engine/i18n/TranslationSystemImpl.java
  engine/src/main/java/org/terasology/engine/i18n/assets/Translation.java
  engine/src/main/java/org/terasology/engine/i18n/assets/TranslationData.java
  engine/src/main/java/org/terasology/engine/i18n/assets/TranslationFormat.java
  engine/src/main/java/org/terasology/engine/logic/console/commands/CoreCommands.java
  engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/NUIEditorSettingsScreen.java
Labels: Type: Refactoring

#4867 chore: remove SubmersibleCamera abstraction
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/renderer/HeadlessWorldRenderer.java
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/renderer/NullCamera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/OpenVRStereoCamera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/PerspectiveCamera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/SubmersibleCamera.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java
Labels: Type: Chore, Type: Refactoring
