Repository MovingBlocks/Terasology, pull requests merged in 2021-05, with the labels that each got.

#4635 chore: remove deprecated ProtobufSerializer
  engine-tests/src/test/java/org/terasology/engine/persistence/serializers/TypeSerializerTest.java
  engine-tests/src/test/java/org/terasology/engine/persistence/serializers/VectorTypeSerializerTest.java
  engine-tests/src/test/java/org/terasology/engine/persistence/typeHandling/mathTypes/BlockAreaTypeHandlerTest.java
  engine/src/main/java/org/terasology/engine/persistence/serializers/ProtobufSerializer.java
Labels: Stabilization

#4649 build(module_build): use same DependencyInfo -> String logic for modules and engine
  build-logic/src/main/kotlin/org/terasology/gradology/module_build.kt
Labels: Blocker, Bug, Logistics

#4531 fix: save world gen facet information in manifest
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/CreateWorldEntity.java
  engine/src/main/java/org/terasology/engine/game/GameManifest.java
  engine/src/main/java/org/terasology/engine/persistence/internal/ReadWriteStorageManager.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/GameManifestProvider.java
Labels: Bug, Stabilization

#4619 fix: avoid writing window size of 0 to the config
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglGraphics.java
Labels: Bug

#4665 doc: Update README
  README.markdown
Labels: Documentation

#4669 build(github): add common 'labels.json'; update release drafter config
  .github/labels.json
  .github/release-drafter-config.yml
  .github/workflows/release-draft.yml
Labels: Category: Build/CI

#4657 chore: replace ViewFrustum with JOML FrustumIntersection
  engine/src/main/java/org/terasology/engine/rendering/cameras/Camera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/OpenVRStereoCamera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/OrthographicCamera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/ViewFrustum.java
  engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java
Labels: Type: Chore

#4616 chore: add primative mesh producer in-place of OpenGLUtils#renderFullscreenQuad
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/ScreenQuadMeshProducer.java
  engine/src/main/java/org/terasology/engine/rendering/logic/MeshRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLUtils.java
  engine/src/main/resources/org/terasology/engine/assets/shaders/post_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/post_vert.glsl
Labels: Type: Chore

#4676 fix: texture3d is deprecated after 120 for nvidia cards
  engine/src/main/resources/org/terasology/engine/assets/shaders/post_frag.glsl
Labels: Topic: Rendering, Type: Bug

#4674 fix: UI in game will get scaled with chaning "Resolution Scale" in world
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/LwjglCanvasRenderer.java
Labels: Topic: Rendering, Type: Bug

#4677 fix: replace gl_TexCoord with v_uv0 for post_frag
  engine/src/main/resources/org/terasology/engine/assets/shaders/post_frag.glsl
Labels: Topic: Rendering, Type: Bug

#4672 Fix for version file for launcher + increment to next major release
  Jenkinsfile
  engine-tests/src/main/resources/org/terasology/unittest/module.txt
  engine/src/main/resources/org/terasology/engine/engine-module.txt
Labels: Category: Build/CI

#4675 chore(telemetry): drop module scanning from telemetry.Metrics
  engine/src/main/java/org/terasology/engine/telemetry/Metrics.java
Labels: Category: Performance, Type: Chore

#4692 chore: remove unused displaylist in SpriteParticleRenderer
  engine/src/main/java/org/terasology/engine/particles/rendering/SpriteParticleRenderer.java
Labels: Topic: Rendering, Type: Chore

#4683 chore: migrate blur to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/blur_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/blur_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4664 chore: replace TypeMap with ClassToInstanceMap
  engine/src/main/java/org/terasology/engine/utilities/collection/TypeMap.java
  engine/src/main/java/org/terasology/engine/world/generation/RegionImpl.java
Labels: Type: Chore

#4691 fix: update FloatingTextRender with GLSL change for mesh layout
  engine/src/main/java/org/terasology/engine/rendering/logic/FloatingTextRenderer.java
Labels: Topic: Rendering, Type: Bug

#4694 fix: don't restrict world generators to a certain type of module source
  engine-tests/build.gradle
  engine-tests/src/main/java/org/terasology/unittest/stubs/StubWorldGenerator.java
  engine-tests/src/test/java/org/terasology/engine/world/generator/internal/WorldGeneratorManagerTest.java
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/world/generator/internal/WorldGeneratorManager.java
Labels: Topic: UI/UX, Topic: WorldGen, Type: Bug

#4695 chore(telemetry): drop module scanning from telemetry.TelemetryScreen
  engine/src/main/java/org/terasology/engine/telemetry/TelemetryScreen.java
Labels: Category: Performance, Type: Chore

#4697 chore: add doc and todo on module presence as source check
  engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/AbstractEditorScreen.java
Labels: Category: Doc, Type: Chore

#4666 chore: inline ImmutableCollectionUtil within CollectionWidgetFactory
  engine/src/main/java/org/terasology/engine/rendering/nui/widgets/types/CollectionWidgetFactory.java
  engine/src/main/java/org/terasology/engine/utilities/collection/ImmutableCollectionUtil.java
Labels: Type: Chore

#4660 fix(json-config-loading): Fix handling invalid AutoConfigs and config writing
  engine/src/main/java/org/terasology/engine/config/flexible/AutoConfigManager.java
Labels: Blocker, Type: Bug

#4636 chore: remove GLBufferPool
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/GLBufferPool.java
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglGraphicsManager.java
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglRenderingSubsystemFactory.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/ChunkMeshTypeHandler.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMesh.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkTessellator.java
  engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java
Labels: Topic: Stabilization, Type: Chore

#4663 chore: remove unused collection utilities
  engine/src/main/java/org/terasology/engine/utilities/collection/TypeListMultimap.java
  engine/src/main/java/org/terasology/engine/utilities/collection/TypeMultimap.java
Labels: Type: Chore

#4667 chore: clean up usage of getPosition for chunk
  engine/src/main/java/org/terasology/engine/world/chunks/localChunkProvider/LocalChunkProvider.java
Labels: Type: Chore

#4689 bugfix: correct getModulesProviding for screenquad
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/ScreenQuadMeshProducer.java
Labels: Type: Bug

#4693 bugfix: update hasInSight with camera position instead of viewPosition
  engine/src/main/java/org/terasology/engine/rendering/cameras/Camera.java
Labels: Topic: Rendering, Type: Bug

#4700 fix: remove restriction of input bindings to source modules
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java
Labels: Type: Bug

#4696 fix(engine): explicitly register `TypeHandler.class` as representative for TypeHandlerLibrary
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
Labels: Blocker, Category: Build/CI, Topic: Architecture, Topic: Stabilization, Type: Bug

#4703 test(ModuleManager): new tests for existing behavior
  engine-tests/src/main/java/org/terasology/unittest/stubs/StubSubsystem.java
  engine-tests/src/test/java/org/terasology/engine/core/module/ModuleManagerTest.java
Labels: Category: Test/QA

#4648 test: provide a stub PathManager during tests
  engine-tests/src/main/java/org/terasology/engine/Environment.java
  engine-tests/src/main/java/org/terasology/engine/HeadlessEnvironment.java
  engine-tests/src/main/java/org/terasology/engine/ModuleEnvironmentTest.java
  engine-tests/src/main/java/org/terasology/engine/TerasologyTestingEnvironment.java
  engine-tests/src/main/java/org/terasology/engine/core/PathManagerProvider.java
  engine-tests/src/test/java/org/terasology/config/flexible/AutoConfigManagerTest.java
  engine-tests/src/test/java/org/terasology/engine/core/module/ModuleManagerTest.java
  engine-tests/src/test/java/org/terasology/engine/persistence/internal/StorageManagerTest.java
  engine-tests/src/test/java/org/terasology/rendering/nui/layers/mainMenu/savedGames/GameProviderTest.java
  engine/src/main/java/org/terasology/engine/config/Config.java
  engine/src/main/java/org/terasology/engine/config/flexible/AutoConfigManager.java
  engine/src/main/java/org/terasology/engine/core/PathManager.java
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseWorld.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleInstaller.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
  engine/src/main/java/org/terasology/engine/core/module/SandboxFileManager.java
  engine/src/main/java/org/terasology/engine/logic/behavior/BehaviorSystem.java
  engine/src/main/java/org/terasology/engine/logic/behavior/CollectiveBehaviorSystem.java
  engine/src/main/java/org/terasology/engine/logic/console/commands/CoreCommands.java
  engine/src/main/java/org/terasology/engine/network/internal/ClientConnectionHandler.java
  engine/src/main/java/org/terasology/engine/network/internal/ServerConnectListManager.java
  engine/src/main/java/org/terasology/engine/persistence/internal/ReadWriteStorageManager.java
  engine/src/main/java/org/terasology/engine/persistence/internal/SaveTransaction.java
  engine/src/main/java/org/terasology/engine/recording/EventSystemReplayImpl.java
  engine/src/main/java/org/terasology/engine/recording/RecordAndReplaySerializer.java
  engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/NUIEditorScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/NUISkinEditorScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/NameRecordingScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/RecordScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/ReplayScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectGameScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/savedGames/GameProvider.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLShader.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/ScreenGrabber.java
  engine/src/main/java/org/terasology/engine/utilities/Jvm.java
  engine/src/main/java/org/terasology/engine/world/block/tiles/WorldAtlasImpl.java
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
  facades/TeraEd/src/main/java/org/terasology/editor/TeraEd.java
Labels: Category: Test/QA

#4701 ci: split Analytics stage
  Jenkinsfile
Labels: Category: Build/CI, Status: Needs Testing, Type: Improvement

#4706 bugfix: fix opengl memory leak in OpenGLMesh
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMesh.java
Labels: Topic: Rendering, Type: Bug

#4710 style: fix AnnotationUseStyle
  engine-tests/src/test/java/org/terasology/engine/ComponentSystemManagerTest.java
  engine/src/main/java/org/terasology/engine/config/flexible/ui/ConstraintWidgetFactory.java
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/LoadingChunkEventSystem.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
  engine/src/main/java/org/terasology/engine/logic/actions/PlaySoundAction.java
  engine/src/main/java/org/terasology/engine/logic/ai/HierarchicalAISystem.java
  engine/src/main/java/org/terasology/engine/logic/ai/SimpleAISystem.java
  engine/src/main/java/org/terasology/engine/logic/characters/CharacterSystem.java
  engine/src/main/java/org/terasology/engine/logic/characters/ServerCharacterPredictionSystem.java
  engine/src/main/java/org/terasology/engine/logic/characters/VisualCharacterSystem.java
  engine/src/main/java/org/terasology/engine/logic/characters/interactions/InteractionSystem.java
  engine/src/main/java/org/terasology/engine/logic/debug/ChunkEventErrorLogger.java
  engine/src/main/java/org/terasology/engine/logic/location/LocationChangedSystem.java
  engine/src/main/java/org/terasology/engine/logic/nameTags/NameTagClientSystem.java
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/engine/logic/players/MenuControlSystem.java
  engine/src/main/java/org/terasology/engine/logic/players/PlayerSystem.java
  engine/src/main/java/org/terasology/engine/logic/selection/LocalPlayerBlockSelectionByItemSystem.java
  engine/src/main/java/org/terasology/engine/network/internal/NetworkEntitySystem.java
  engine/src/main/java/org/terasology/engine/particles/ParticleSystemManagerImpl.java
  engine/src/main/java/org/terasology/engine/particles/functions/affectors/AccelerationAffectorFunction.java
  engine/src/main/java/org/terasology/engine/particles/functions/affectors/VelocityAffectorFunction.java
  engine/src/main/java/org/terasology/engine/particles/functions/generators/ColorRangeGeneratorFunction.java
  engine/src/main/java/org/terasology/engine/particles/functions/generators/EnergyRangeGeneratorFunction.java
  engine/src/main/java/org/terasology/engine/particles/functions/generators/PositionRangeGeneratorFunction.java
  engine/src/main/java/org/terasology/engine/particles/functions/generators/ScaleRangeGeneratorFunction.java
  engine/src/main/java/org/terasology/engine/particles/functions/generators/TextureOffsetGeneratorFunction.java
  engine/src/main/java/org/terasology/engine/particles/functions/generators/VelocityRangeGeneratorFunction.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/factories/AssetTypeHandlerFactory.java
  engine/src/main/java/org/terasology/engine/physics/engine/PhysicsSystem.java
  engine/src/main/java/org/terasology/engine/rendering/logic/FloatingTextRenderer.java
  engine/src/main/java/org/terasology/engine/utilities/ReflectionUtil.java
  engine/src/main/java/org/terasology/engine/world/block/entity/neighbourUpdate/NeighbourBlockFamilyUpdateSystem.java
  engine/src/main/java/org/terasology/engine/world/block/entity/placement/BlockPlacingSystem.java
  engine/src/main/java/org/terasology/engine/world/block/structure/BlockStructuralSupportSystem.java
  engine/src/main/java/org/terasology/engine/world/internal/EntityAwareWorldProvider.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/TypeHandlerLibrary.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/annotations/SerializedName.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/ArrayTypeHandler.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/RuntimeDelegatingTypeHandler.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/factories/ArrayTypeHandlerFactory.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/factories/CollectionTypeHandlerFactory.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/factories/MapTypeHandlerFactory.java
Labels: Topic: Stabilization, Type: Bug, Type: Chore, Type: Refactoring

#4678 chore: migrate tone mapping to GLSL 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/toneMapping_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/toneMapping_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4682 chore: migrate sobel to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/sobel_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/sobel_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4717 fix: version directives need to come before comments
  engine/src/main/resources/org/terasology/engine/assets/shaders/sobel_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/sobel_vert.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/toneMapping_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/toneMapping_vert.glsl
Labels: Blocker, Topic: Rendering, Type: Bug

#4681 chore: migrate initialPost to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/initialPost_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/initialPost_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4680 chore: migrate lightshafts to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightShafts_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightShafts_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4686 chore: migrate highpass to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/highPass_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/highPass_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4687 chore: migrate downsampler to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/downSampler_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/downSampler_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4684 chore: migrate vignette to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/vignette_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/vignette_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4690 chore: migrate lightBufferPass to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightBufferPass_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/lightBufferPass_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4688 chore: migrate prePostComposite to glsl 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/prePostComposite_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/prePostComposite_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4679 chore: migrate ssao 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/ssao_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/ssao_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4685 chore: remove unused shaders
  engine/src/main/resources/org/terasology/engine/assets/materials/testMaterial.mat
  engine/src/main/resources/org/terasology/engine/assets/shaders/animateOpacity_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/animateOpacity_vert.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/fancy/testShader.info
  engine/src/main/resources/org/terasology/engine/assets/shaders/fancy/testShader_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/fancy/testShader_vert.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/ocDistortion_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/ocDistortion_vert.glsl
Labels: Topic: Rendering, Type: Chore

#4714 chore: mark methods using deprecated opengl for removal camera
  engine/src/main/java/org/terasology/engine/rendering/cameras/Camera.java
Labels: Topic: Rendering, Type: Chore

#4715 rendering: fix canvas fbo render with GL330
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/LwjglCanvasRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/LwjglFrameBufferObject.java
Labels: Topic: Rendering, Type: Bug

#4659 chore: combine NativeHelper and OS
  engine/src/main/java/org/terasology/engine/rendering/openvrprovider/OpenVRProvider.java
  engine/src/main/java/org/terasology/engine/utilities/LWJGLHelper.java
  engine/src/main/java/org/terasology/engine/utilities/NativeHelper.java
  engine/src/main/java/org/terasology/engine/utilities/OS.java
Labels: Type: Chore

#4651 Bugfix: add excluded entity for rayTrace
  engine/src/main/java/org/terasology/engine/physics/bullet/BulletPhysics.java
Labels: Topic: Physics, Type: Bug

#4723 fix(DiscordRPC): NPE on shutdown
  subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCSystem.java
Labels: Size: S, Type: Bug

#4724 feat?: Don't swallow exceptions in EventSystem#invoke
  engine/src/main/java/org/terasology/engine/entitySystem/event/internal/EventSystemImpl.java
Labels: Category: Crash, Topic: Stabilization, Type: Improvement

#4719 style: fix checkstyle findings
  engine-tests/src/test/java/org/terasology/engine/ComponentSystemManagerTest.java
  engine-tests/src/test/java/org/terasology/engine/core/module/ClasspathCompromisingModuleFactoryTest.java
  engine-tests/src/test/java/org/terasology/engine/subsystem/config/BindsSubsystemTest.java
  engine-tests/src/test/java/org/terasology/logic/characters/VisualCharacterSystemTest.java
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/event/VectorEventSerializer.java
  engine/src/jmh/java/org/terasology/benchmark/reflectFactory/GetterSetterComponent.java
  engine/src/main/java/org/terasology/engine/audio/openAL/streamingSound/OpenALStreamingSound.java
  engine/src/main/java/org/terasology/engine/config/AudioConfig.java
  engine/src/main/java/org/terasology/engine/config/facade/BindsConfiguration.java
  engine/src/main/java/org/terasology/engine/config/facade/BindsConfigurationImpl.java
  engine/src/main/java/org/terasology/engine/config/facade/InputDeviceConfiguration.java
  engine/src/main/java/org/terasology/engine/config/facade/InputDeviceConfigurationImpl.java
  engine/src/main/java/org/terasology/engine/config/flexible/internal/SettingImpl.java
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/CreateWorldEntity.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
  engine/src/main/java/org/terasology/engine/core/module/StandardModuleExtension.java
  engine/src/main/java/org/terasology/engine/core/subsystem/config/BindsManager.java
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/Lwjgl2Sync.java
  engine/src/main/java/org/terasology/engine/entitySystem/entity/internal/PojoEntityPool.java
  engine/src/main/java/org/terasology/engine/entitySystem/sectors/SectorSimulationSystem.java
  engine/src/main/java/org/terasology/engine/identity/storageServiceClient/StorageServiceWorker.java
  engine/src/main/java/org/terasology/engine/input/internal/BindCommands.java
  engine/src/main/java/org/terasology/engine/logic/afk/AfkClientSystem.java
  engine/src/main/java/org/terasology/engine/logic/behavior/core/BaseAction.java
  engine/src/main/java/org/terasology/engine/network/internal/ClientHandshakeHandler.java
  engine/src/main/java/org/terasology/engine/particles/ParticlePool.java
  engine/src/main/java/org/terasology/engine/particles/rendering/SpriteParticleRenderer.java
  engine/src/main/java/org/terasology/engine/particles/updating/ParticleUpdaterImpl.java
  engine/src/main/java/org/terasology/engine/recording/EventCopier.java
  engine/src/main/java/org/terasology/engine/recording/RecordedEventSerializer.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/ScreenQuadMeshProducer.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/Camera.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/SubmersibleCamera.java
  engine/src/main/java/org/terasology/engine/rendering/dag/Node.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/DeathScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/NewGameScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/widgets/types/ArrayWidgetFactory.java
  engine/src/main/java/org/terasology/engine/rendering/nui/widgets/types/CollectionWidgetFactory.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLShader.java
  engine/src/main/java/org/terasology/engine/utilities/Jvm.java
  engine/src/main/java/org/terasology/engine/utilities/ReflectionUtil.java
  engine/src/main/java/org/terasology/engine/world/block/BlockAreac.java
  engine/src/main/java/org/terasology/engine/world/block/BlockRegionc.java
  engine/src/main/java/org/terasology/engine/world/generation/facets/base/BaseStrictlySparseFieldFacet2D.java
  engine/src/main/java/org/terasology/engine/world/zones/SeededNoiseLayerThickness.java
Labels: Category: Test/QA, Type: Bug, Type: Chore

#4725 fix: ensure absolute path in PathManager
  engine/src/main/java/org/terasology/engine/core/PathManager.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
Labels: Type: Bug

#4732 fix(rendering): correct order of initilization for GLSLShader
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLShader.java
Labels: Topic: Rendering, Type: Bug

#4722 chore: rename engine-module.txt to module.txt
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
  engine/src/main/resources/org/terasology/engine/module.txt
Labels: Status: Needs Testing, Type: Chore

#4705 feature: rework location change event
  engine/src/main/java/org/terasology/engine/logic/location/LocationChangedEvent.java
  engine/src/main/java/org/terasology/engine/logic/location/LocationChangedSystem.java
  engine/src/main/java/org/terasology/engine/logic/location/LocationComponent.java
Labels: Category: Doc, Type: Improvement

#4712 rendering: migrate extension logic
  engine/src/main/java/org/terasology/engine/rendering/ShaderManagerLwjgl.java
Labels: Topic: Rendering, Type: Chore

#4731 refactor(rendering): rework AABBRenderer with Mesh and update default glsl
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/engine/rendering/AABBRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/StandardMeshData.java
  engine/src/main/resources/org/terasology/engine/assets/shaders/default_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/default_vert.glsl
Labels: Type: Refactoring

#4734 fix: broken wiki link in README
  README.markdown
Labels: Category: Doc, Type: Bug

#4727 perf: reuse Vector3f/Quaternionf between game ticks
  engine/src/main/java/org/terasology/engine/audio/system/AudioSystem.java
Labels: Category: Performance

#4720 refactor(rendering): replace defaultTextured with outputPass shader
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/renderer/ShaderManagerHeadless.java
  engine/src/main/java/org/terasology/engine/rendering/ShaderManager.java
  engine/src/main/java/org/terasology/engine/rendering/ShaderManagerLwjgl.java
  engine/src/main/java/org/terasology/engine/rendering/world/selection/BlockSelectionRenderer.java
  engine/src/main/resources/org/terasology/engine/assets/shaders/defaultTextured_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/defaultTextured_vert.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/outputPass_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/outputPass_vert.glsl
Labels: Topic: Rendering, Type: Refactoring

#4721 refactor(rendering): migrate ssaoBlur for GLSL 330
  engine/src/main/resources/org/terasology/engine/assets/shaders/ssaoBlur_frag.glsl
  engine/src/main/resources/org/terasology/engine/assets/shaders/ssaoBlur_vert.glsl
Labels: Topic: Rendering, Type: Chore, Type: Refactoring
