Repository MovingBlocks/Terasology, pull requests merged in 2021-08, with the labels that each got.

#4824 fix: collide with characters instead of walking through
  engine/src/main/java/org/terasology/engine/logic/characters/CharacterMovementComponent.java
Labels: Category: Gameplay Content, Size: S, Topic: Physics, Topic: UI/UX, Type: Bug

#4829 fix: resolve issue when loading a world a second time
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/core/bootstrap/EnvironmentSwitchHandler.java
  engine/src/main/java/org/terasology/engine/core/modes/StateIngame.java
  engine/src/main/java/org/terasology/engine/core/modes/StateLoading.java
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseRendering.java
  engine/src/main/java/org/terasology/engine/core/subsystem/rendering/ModuleRenderingSubsystem.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLMaterial.java
  engine/src/main/java/org/terasology/engine/world/block/DefaultColorSource.java
Labels: Type: Bug, Topic: UI/UX, Topic: Stabilization, Category: Crash

#4833 feat: add priority to Updates annotation of facet providers
  engine/src/main/java/org/terasology/engine/world/generation/UpdatePriority.java
  engine/src/main/java/org/terasology/engine/world/generation/Updates.java
  engine/src/main/java/org/terasology/engine/world/generation/WorldBuilder.java
Labels: Type: Improvement, Topic: WorldGen

#4840 fix: resolve Advance World Settings issue
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
Labels: Type: Bug, Type: Chore

#4841 fix: Better handling of ComponentSystem loading with optional dependencies
  engine/src/main/java/org/terasology/engine/core/ComponentSystemManager.java
Labels: Type: Bug, Category: Build/CI

#4157 chore[facade]: use picocli for processing command line options
  .idea/misc.xml
  .idea/runConfigurations/TerasologyPC.xml
  .idea/runConfigurations/TerasologyPC__2nd_client_.xml
  .idea/runConfigurations/TerasologyPC__3rd_client_.xml
  .idea/runConfigurations/TerasologyPC__CR_enabled_.xml
  .idea/runConfigurations/TerasologyPC__EXTREME_8GB_.xml
  .idea/runConfigurations/TerasologyPC__Headless_.xml
  .idea/runConfigurations/TerasologyPC__Java_FlightRecorder_.xml
  .idea/runConfigurations/TerasologyPC__Splash_disabled_.xml
  .idea/runConfigurations/TerasologyPC__load_latest_.xml
  .idea/runConfigurations/TerasologyPC__no_audio_.xml
  .idea/runConfigurations/TerasologyPC__no_saves_.xml
  .idea/runConfigurations/TerasologyPC__permissive_security_.xml
  .idea/runConfigurations/TerasologyPC__recreate_latest_.xml
  build-logic/src/main/kotlin/org/terasology/gradology/exec.kt
  docs/Playing.md
  engine/src/main/java/org/terasology/engine/core/PathManager.java
  facades/PC/build.gradle.kts
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Type: Improvement, Breaking Change, Type: Chore

#4842 chore: adjust default logback configuration
  engine-tests/src/test/resources/logback.xml
  facades/PC/src/main/resources/logback.xml
Labels: Type: Chore

#4844 chore: add maven repo that contains jpastebin
  build-logic/src/main/kotlin/terasology-repositories.gradle.kts
Labels: Type: Chore

#4845 fix(build): use Maps from guava, not Google API Client
  engine/src/main/java/org/terasology/engine/physics/bullet/BulletPhysics.java
Labels: Type: Bug, Category: Build/CI, Size: S

#4846 test: have IntelliJ ask if tests should be run by itself or gradle
  build.gradle
Labels: Category: Test/QA

#4848 feat: add `./gw completion` command.
  gradle/gooeycli/src/main/groovy/org/terasology/cli/GooeyCLI.groovy
  gradle/gooeycli/src/main/groovy/org/terasology/cli/commands/BashCompletitionCommand.groovy
Labels: Type: Improvement

#4849 feat: add random distribution utilities from AnotherWorld
  engine/src/main/java/org/terasology/engine/utilities/random/DiscreteDistribution.java
  engine/src/main/java/org/terasology/engine/utilities/random/PDist.java
Labels: Type: Improvement

#4794 perf: improve performance of mesh generator for chunks
  engine/src/main/java/org/terasology/engine/math/Side.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/BlockMeshGeneratorSingleShape.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkTessellator.java
  engine/src/main/java/org/terasology/engine/world/block/Block.java
  engine/src/main/java/org/terasology/engine/world/block/BlockAppearance.java
  engine/src/main/java/org/terasology/engine/world/block/BlockPart.java
  engine/src/main/java/org/terasology/engine/world/block/loader/BlockFamilyDefinitionFormat.java
Labels: Topic: Rendering, Type: Chore

#4147 feat: set limits for maximum memory use.
  facades/PC/build.gradle.kts
  facades/PC/src/main/java/org/terasology/engine/DataSizeConverter.java
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
  facades/PC/src/test/java/org/terasology/engine/DataSizeConverterTest.java
Labels: Category: Build/CI, Category: Performance, Type: Improvement

#4852 feat: Add parallel module get
  gradle/gooeycli/src/main/groovy/org/terasology/cli/commands/module/GetCommand.groovy
  gradle/gooeycli/src/main/groovy/org/terasology/cli/util/Constants.groovy
  gradle/gooeycli/src/main/groovy/org/terasology/cli/util/ModuleIndex.groovy
Labels: Type: Improvement

#4847 fix: enable block tinting in LOD chunks
  engine/src/main/java/org/terasology/engine/rendering/primitives/BlockMeshGeneratorSingleShape.java
  engine/src/main/java/org/terasology/engine/world/block/BlockColorSource.java
  engine/src/main/java/org/terasology/engine/world/block/ColorProvider.java
  engine/src/main/java/org/terasology/engine/world/block/DefaultColorSource.java
Labels: Type: Bug

#4859 build(facade): oops, junit was supposed to be a test-only dependency
  facades/PC/build.gradle.kts
  facades/PC/src/main/java/org/terasology/engine/DataSizeConverter.java
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Category: Doc, Category: Build/CI, Size: S

#4843 feat: hide NotificationOverlay (chat box) if HUD is hidden
  engine/src/main/java/org/terasology/engine/config/RenderingDebugConfig.java
  engine/src/main/java/org/terasology/engine/logic/console/ui/NotificationOverlay.java
Labels: Topic: UI/UX, Type: Improvement

#4799 refactor: replace usage of ThreadManagerSubsystem with reactor Scheduler
  .idea/dictionaries/kevint.xml
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/core/GameScheduler.java
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/core/modes/StateIngame.java
  engine/src/main/java/org/terasology/engine/core/module/ExternalApiWhitelist.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
  engine/src/main/java/org/terasology/engine/core/subsystem/common/ThreadManager.java
  engine/src/main/java/org/terasology/engine/core/subsystem/common/ThreadManagerSubsystem.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/metrics/RunningThreadsMode.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/ScreenGrabber.java
  facades/PC/build.gradle.kts
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Type: Refactoring, Topic: Concurrency

#4870 chore: some lintings and suggested simplifications
  .idea/dictionaries/kevint.xml
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMesh.java
  engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java
  engine/src/main/java/org/terasology/engine/world/chunks/Chunk.java
Labels: Size: S, Type: Chore

#4873 chore: upgrade crashreporter dependency 4.1.0 -> 4.2.0
  engine/build.gradle
Labels: Size: S, Type: Chore
