Repository MovingBlocks/Terasology, pull requests merged in 2021-04, with the labels that each got.

#4599 feat(player-config): migrate `PlayerConfig` to AutoConfig
  engine-tests/src/test/java/org/terasology/config/flexible/ui/SettingWidgetFactoryTest.java
  engine/src/main/java/org/terasology/engine/config/Config.java
  engine/src/main/java/org/terasology/engine/config/PlayerConfig.java
  engine/src/main/java/org/terasology/engine/config/RootConfig.java
  engine/src/main/java/org/terasology/engine/config/SystemConfig.java
  engine/src/main/java/org/terasology/engine/config/flexible/AutoConfigManager.java
  engine/src/main/java/org/terasology/engine/config/flexible/bindings/MappingBinding.java
  engine/src/main/java/org/terasology/engine/config/flexible/bindings/SettingBinding.java
  engine/src/main/java/org/terasology/engine/config/flexible/constraints/ColorConstraint.java
  engine/src/main/java/org/terasology/engine/config/flexible/constraints/LocaleConstraint.java
  engine/src/main/java/org/terasology/engine/config/flexible/constraints/PredicateWithDescription.java
  engine/src/main/java/org/terasology/engine/config/flexible/constraints/StringConstraint.java
  engine/src/main/java/org/terasology/engine/config/flexible/ui/AutoConfigScreen.java
  engine/src/main/java/org/terasology/engine/config/flexible/ui/AutoConfigWidgetFactory.java
  engine/src/main/java/org/terasology/engine/config/flexible/ui/ColorConstraintWidgetFactory.java
  engine/src/main/java/org/terasology/engine/config/flexible/ui/DefaultConstraintWidgetFactory.java
  engine/src/main/java/org/terasology/engine/config/flexible/ui/LocaleConstraintWidgetFactory.java
  engine/src/main/java/org/terasology/engine/config/flexible/ui/SettingWidgetFactory.java
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/SetupLocalPlayer.java
  engine/src/main/java/org/terasology/engine/i18n/TranslationSystemImpl.java
  engine/src/main/java/org/terasology/engine/logic/characters/GazeAuthoritySystem.java
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/engine/network/internal/ClientConnectionHandler.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/EnterUsernamePopup.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/JoinGameScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectGameScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectionScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/settings/PlayerSettingsScreen.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java
  engine/src/main/java/org/terasology/engine/telemetry/metrics/GameConfigurationMetric.java
  engine/src/main/resources/assets/i18n/menu.lang
  engine/src/main/resources/assets/i18n/menu_en.lang
  engine/src/main/resources/assets/ui/config/autoConfigScreen.ui
  engine/src/main/resources/assets/ui/config/colorPickerWidget.ui
  engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui
  subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordAutoConfig.java
  subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCSubSystem.java
Labels: Bug, Enhancement, UI

#4598 chore: update to TeraNUI 3.0 from 1.5, for gestalt separation
  engine-tests/src/main/java/org/terasology/engine/HeadlessEnvironment.java
  engine-tests/src/main/java/org/terasology/engine/ModuleEnvironmentTest.java
  engine-tests/src/test/java/org/terasology/entitySystem/metadata/internal/MetadataBuilderTest.java
  engine-tests/src/test/java/org/terasology/persistence/typeHandling/event/VectorEventSerializer.java
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/core/bootstrap/EnvironmentSwitchHandler.java
  engine/src/main/java/org/terasology/engine/core/module/ExternalApiWhitelist.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
  engine/src/main/java/org/terasology/engine/entitySystem/metadata/ComponentLibrary.java
  engine/src/main/java/org/terasology/engine/entitySystem/metadata/ComponentMetadata.java
  engine/src/main/java/org/terasology/engine/entitySystem/metadata/EventLibrary.java
  engine/src/main/java/org/terasology/engine/entitySystem/metadata/EventMetadata.java
  engine/src/main/java/org/terasology/engine/logic/behavior/nui/BehaviorNodeFactory.java
  engine/src/main/java/org/terasology/engine/logic/console/commands/CoreCommands.java
  engine/src/main/java/org/terasology/engine/logic/console/suggesters/SkinSuggester.java
  engine/src/main/java/org/terasology/engine/network/internal/NetworkSystemImpl.java
  engine/src/main/java/org/terasology/engine/persistence/internal/EntityStorer.java
  engine/src/main/java/org/terasology/engine/persistence/internal/GlobalStoreBuilder.java
  engine/src/main/java/org/terasology/engine/persistence/serializers/ComponentSerializer.java
  engine/src/main/java/org/terasology/engine/persistence/serializers/EntitySerializer.java
  engine/src/main/java/org/terasology/engine/persistence/serializers/PrefabSerializer.java
  engine/src/main/java/org/terasology/engine/persistence/serializers/WorldSerializerImpl.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/UISkinTypeHandler.java
  engine/src/main/java/org/terasology/engine/rendering/nui/CoreScreenLayer.java
  engine/src/main/java/org/terasology/engine/rendering/nui/NUIManager.java
  engine/src/main/java/org/terasology/engine/rendering/nui/asset/UIFormat.java
  engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/NUISkinEditorScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/NUIManagerInternal.java
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/WidgetLibrary.java
  engine/src/main/java/org/terasology/engine/rendering/nui/internal/WidgetMetadata.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/UniverseSetupScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/skin/UISkinFormat.java
  engine/src/main/java/org/terasology/engine/rendering/nui/skin/UISkinWithUrn.java
  engine/src/main/java/org/terasology/engine/utilities/Assets.java
  engine/src/main/java/org/terasology/engine/world/block/family/BlockFamilyLibrary.java
  engine/src/main/java/org/terasology/engine/world/generator/plugin/DefaultWorldGeneratorPluginLibrary.java
  facades/TeraEd/src/main/java/org/terasology/editor/properties/ReflectionProvider.java
  subsystems/TypeHandlerLibrary/build.gradle.kts
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/Serializer.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/TypeHandlerLibrary.java
Labels: Architecture

#4615 chore: refactor physics voxel world system
  engine/src/main/java/org/terasology/engine/physics/bullet/VoxelWorldSystem.java
  engine/src/main/java/org/terasology/engine/physics/bullet/world/BulletVoxelBlockWorld.java
  engine/src/main/java/org/terasology/engine/physics/bullet/world/VoxelBlockFluidWorld.java
  engine/src/main/java/org/terasology/engine/physics/bullet/world/VoxelBlockWorld.java
  engine/src/main/java/org/terasology/engine/physics/bullet/world/VoxelWorld.java
  engine/src/main/java/org/terasology/engine/physics/engine/VoxelLiquidWorldSystem.java
  engine/src/main/java/org/terasology/engine/physics/engine/VoxelWorldSystem.java
Labels: Performance, Physics

#4602 fix: restore version info
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/version/TerasologyVersion.java
Labels: Blocker, Bug

#4611 build: add tasks for 'unit' and 'integration' tests
  build-logic/src/main/kotlin/terasology-module.gradle.kts
  engine-tests/build.gradle
Labels: Logistics

#4609 feat: allow repeated jumping by key press
  engine/src/main/java/org/terasology/engine/input/binds/movement/JumpButton.java
  engine/src/main/java/org/terasology/engine/logic/characters/CharacterMoveInputEvent.java
  engine/src/main/java/org/terasology/engine/logic/characters/KinematicCharacterMover.java
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/engine/recording/EventCopier.java
Labels: Enhancement

#4597 feat(entitySystem): Introduce DoNotPersist annotation
  engine-tests/src/test/java/org/terasology/persistence/EntitySerializerTest.java
  engine/src/main/java/org/terasology/engine/entitySystem/DoNotPersist.java
  engine/src/main/java/org/terasology/engine/entitySystem/entity/internal/EntityInfoComponent.java
  engine/src/main/java/org/terasology/engine/entitySystem/metadata/ComponentMetadata.java
  engine/src/main/java/org/terasology/engine/persistence/internal/EntityRestorer.java
  engine/src/main/java/org/terasology/engine/persistence/internal/EntityStorer.java
  engine/src/main/java/org/terasology/engine/persistence/internal/GlobalStoreBuilder.java
  engine/src/main/java/org/terasology/engine/persistence/internal/GlobalStoreLoader.java
  engine/src/main/java/org/terasology/engine/persistence/serializers/PersistenceComponentSerializeCheck.java
Labels: Enhancement

#4624 chore: remove unused gelatinousCube asset
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseGraphics.java
  engine/src/main/resources/assets/shaders/gelatinousCube.info
  engine/src/main/resources/assets/shaders/gelatinousCube_frag.glsl
  engine/src/main/resources/assets/shaders/gelatinousCube_vert.glsl
Labels: Content, Rendering

#4632 logistics: Replace usage of jcenter (shutting down)
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/terasology-repositories.gradle.kts
  build.gradle
  config/groovy/common.groovy
  templates/build.gradle
  templates/facades.gradle
Labels: Logistics

#4630 Fix: Gitignore some more files that Intellij automatically generates.
  .idea/.gitignore
Labels: Logistics

#4631 logistics: use new pre-cached builder image in Jenkins
  Jenkinsfile
  templates/gradle.properties
Labels: Logistics

#4625 fix: correct colliders for LIQUID
  engine/src/main/java/org/terasology/engine/physics/bullet/world/BulletVoxelBlockWorld.java
  engine/src/main/java/org/terasology/engine/physics/bullet/world/VoxelBlockFluidWorld.java
  engine/src/main/java/org/terasology/engine/physics/bullet/world/VoxelBlockWorld.java
Labels: Blocker, Bug
