Repository MovingBlocks/Terasology, pull requests merged in 2021-12, with the labels that each got.

#4964 chore: remove usage of Tesselator for BlockSelectionRenderer
  engine/src/main/java/org/terasology/engine/rendering/world/selection/BlockSelectionRenderer.java
Labels: Type: Chore

#4965 chore: remove deprecated method in Block
  engine/src/main/java/org/terasology/engine/world/block/Block.java
Labels: Type: Chore

#4973 bugfix: resolve BlockSelectionRenderer
  engine/src/main/java/org/terasology/engine/rendering/world/selection/BlockSelectionRenderer.java
Labels: Type: Bug, Topic: Rendering

#4947 feat: micrometer metrics over JMX
  build-logic/src/main/kotlin/org/terasology/gradology/exec.kt
  build.gradle
  config/.gitignore
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/core/GameScheduler.java
  engine/src/main/java/org/terasology/engine/core/subsystem/common/MonitoringSubsystem.java
Labels: Category: Performance, Type: Improvement
