Repository MovingBlocks/Terasology, pull requests merged in 2021-01, with the labels that each got.

#4365 chore: Couple minor tweaks - logic hardening and memory
  engine/src/main/java/org/terasology/logic/behavior/BehaviorSystem.java
  facades/PC/build.gradle.kts
Labels: Logistics

#4343 Fix/transient deps
  build.gradle
  facades/PC/build.gradle.kts
  facades/TeraEd/build.gradle
  modules/build.gradle.kts
  modules/subprojects.settings.gradle
Labels: Bug, Logistics

#4399 perf(optimize): optimize iterator for block region
  engine/src/main/java/org/terasology/world/block/BlockRegion.java
Labels: Performance

#4377 feat(TypeHandler): Add GenericMapTypeHandler for `Map<K, V>`
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/TypeHandlerLibrary.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandler.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/factories/MapTypeHandlerFactory.java
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/TypeHandlerLibraryTest.java
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/factories/MapTypeHandlerFactoryTest.java
Labels: Architecture, Enhancement

#4401 feature(JMH): Migrate benchmarks to JMH
  engine/build.gradle
  engine/src/dev/java/org/terasology/benchmark/AbstractBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/BasicBenchmarkResult.java
  engine/src/dev/java/org/terasology/benchmark/Benchmark.java
  engine/src/dev/java/org/terasology/benchmark/BenchmarkCallback.java
  engine/src/dev/java/org/terasology/benchmark/BenchmarkError.java
  engine/src/dev/java/org/terasology/benchmark/BenchmarkResult.java
  engine/src/dev/java/org/terasology/benchmark/Benchmarks.java
  engine/src/dev/java/org/terasology/benchmark/PrintToConsoleCallback.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArray.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArrayDeserializeFromBuffer.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArrayRead.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArraySerialization.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArraySerializeObject.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArraySerializeToBuffer.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArraySerializeToByteString.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArraySerializeToStreamViaByteArray.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArraySerializeToStreamViaChannel.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/BenchmarkTeraArrayWrite.java
  engine/src/dev/java/org/terasology/benchmark/chunks/arrays/TeraArraysBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/chunks/cache/BenchmarkChunkCache.java
  engine/src/dev/java/org/terasology/benchmark/chunks/cache/ChunkCachesBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/entitySystem/EntityCreateBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/entitySystem/EntitySystemBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/entitySystem/IterateMultipleComponentBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/entitySystem/IterateSingleComponentBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/reflectFactory/ConstructionBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/reflectFactory/FieldAccessBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/reflectFactory/GetterSetterAccessBenchmark.java
  engine/src/dev/java/org/terasology/benchmark/reflectFactory/ReflectFactoryBenchmark.java
  engine/src/jmh/java/org/terasology/benchmark/chunks/arrays/TeraArrayBenchmark.java
  engine/src/jmh/java/org/terasology/benchmark/entitySystem/EntityCreateBenchmark.java
  engine/src/jmh/java/org/terasology/benchmark/entitySystem/IterateComponentsBenchmark.java
  engine/src/jmh/java/org/terasology/benchmark/reflectFactory/GetterSetterComponent.java
  engine/src/jmh/java/org/terasology/benchmark/reflectFactory/ReflectionFactoryBenchmark.java
Labels: Logistics, Performance

#4406 build(jmh): git-ignore generated code
  .gitignore
  build.gradle
Labels: Logistics

#4420 feat(world): add APIs to compute `Chunks` values in-place
  engine/src/main/java/org/terasology/world/chunks/Chunks.java
Labels: Api

#4409 Migrate Omega package from old Jenkins to new, with some minor cleanup / label improvements
  Jenkinsfile
  engine/build.gradle
  engine/src/main/java/org/terasology/version/TerasologyVersion.java
  facades/PC/build.gradle.kts
  templates/VERSION
  templates/version.txt
Labels: Logistics

#4433 perf(world): implement `deflate` for sparse TeraArray (8/16 bit)
  engine/src/main/java/org/terasology/world/chunks/deflate/TeraStandardDeflator.java
Labels: Enhancement, Performance, Stabilization

#4436 fix(joml): Fix always growing relevance region
  engine/src/main/java/org/terasology/world/chunks/localChunkProvider/RelevanceSystem.java
Labels: Bug
