Repository MovingBlocks/Terasology, pull requests merged in 2021-09, with the labels that each got.

#4883 chore: remove unused render utilities
  engine/src/main/java/org/terasology/engine/rendering/RenderMath.java
  engine/src/main/java/org/terasology/engine/rendering/VertexBufferObjectUtil.java
Labels: Type: Chore

#4889 chore: remove deprecated LegacyGsonTypeHandlerAdapter
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/gson/LegacyGsonTypeHandlerAdapter.java
Labels: Type: Chore

#4887 chore: cleanup extra qualification for org.joml from termath migration
  engine-tests/src/test/java/org/terasology/engine/persistence/serializers/TypeSerializerTest.java
  engine-tests/src/test/java/org/terasology/engine/world/EntityAwareWorldProviderTest.java
  engine-tests/src/test/java/org/terasology/math/Diamond3iIteratorTest.java
  engine/src/main/java/org/terasology/engine/audio/openAL/OpenALManager.java
  engine/src/main/java/org/terasology/engine/logic/behavior/nui/BehaviorEditor.java
  engine/src/main/java/org/terasology/engine/logic/characters/CharacterSystem.java
  engine/src/main/java/org/terasology/engine/logic/inventory/ItemPickupAuthoritySystem.java
  engine/src/main/java/org/terasology/engine/logic/players/FirstPersonHeldItemMountPointComponent.java
  engine/src/main/java/org/terasology/engine/network/internal/NetClient.java
  engine/src/main/java/org/terasology/engine/network/internal/NetMessageUtil.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/TypeHandlerLibraryImpl.java
  engine/src/main/java/org/terasology/engine/physics/engine/PhysicsSystem.java
  engine/src/main/java/org/terasology/engine/rendering/nui/contextMenu/ContextMenuScreen.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLSkeletalMesh.java
  engine/src/main/java/org/terasology/engine/rendering/world/ChunkMeshUpdateManager.java
  engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java
  engine/src/main/java/org/terasology/engine/world/block/items/BlockItemSystem.java
  engine/src/main/java/org/terasology/engine/world/chunks/Chunk.java
  engine/src/main/java/org/terasology/engine/world/chunks/Chunks.java
  engine/src/main/java/org/terasology/engine/world/chunks/internal/ChunkImpl.java
  engine/src/main/java/org/terasology/engine/world/chunks/internal/ChunkRelevanceRegion.java
  engine/src/main/java/org/terasology/engine/world/viewer/picker/CirclePickerAll.java
  engine/src/main/java/org/terasology/engine/world/viewer/picker/CirclePickerClosest.java
Labels: Type: Improvement, Type: Chore

#4890 chore(PathManager): remove some "probably isn't needed anymore" code
  engine/src/main/java/org/terasology/engine/core/PathManager.java
Labels: Topic: Stabilization, Size: S, Type: Chore

#4884 fix(autoconfig): fix back-animation to empty screen
  engine/src/main/java/org/terasology/engine/config/flexible/ui/AutoConfigScreen.java
Labels: Type: Bug

#4855 feat: add debug bounding box rendering
  engine/src/main/java/org/terasology/engine/config/RenderingDebugConfig.java
  engine/src/main/java/org/terasology/engine/rendering/logic/BoundingBoxRenderer.java
  engine/src/main/java/org/terasology/engine/rendering/logic/SkeletonRenderer.java
Labels: Topic: Rendering, Type: Improvement

#4892 bugfix: migrate deprecated texture2D
  facades/PC/src/main/resources/splash/shader/frag.glsl
  facades/PC/src/main/resources/splash/shader/vert.glsl
Labels: Type: Bug

#4895 fix(PathManager): working directory should always be a fallback
  engine/src/main/java/org/terasology/engine/core/PathManager.java
Labels: Type: Bug, Category: Build/CI, Blocker, Category: Test/QA, Size: S

#4886 chore: add test cases for IndexResource and address some problems found through test cases
  engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/IndexResourceTest.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/IndexResource.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMesh.java
Labels: Type: Bug, Category: Doc, Category: Test/QA, Type: Chore

#4885 chore: minor fixes and introduce some test cases for VertexResource
  engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexGLAttributeTest.java
  engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexResourceTest.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/GLAttributes.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexResource.java
Labels: Type: Bug, Category: Doc, Category: Test/QA, Type: Chore

#4891 build(IntelliJ): turn on checkstyle.scan-before-checkin
  .idea/checkstyle-idea.xml
  config/gradle/common.gradle
Labels: Category: Build/CI, Size: S

#4857 feat: add commands for visual debugging (bounding boxes, etc.)
  engine/src/main/java/org/terasology/engine/config/RenderingDebugConfig.java
  engine/src/main/java/org/terasology/engine/logic/debug/RenderingDebugCommands.java
Labels: Type: Improvement

#4901 chore(LocationComponent): provide convenience constructor for Vector3i
  engine/src/main/java/org/terasology/engine/logic/location/LocationComponent.java
  engine/src/main/java/org/terasology/engine/world/RelevanceRegionComponent.java
Labels: Size: S, Type: Chore

#4906 feat: add vertex attribute bindings for short and byte
  engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexGLAttributeTest.java
  engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexResourceTest.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/GLAttributes.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexByteAttribute.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexByteAttributeBinding.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexResourceBuilder.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexShortAttribute.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexShortAttributeBinding.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMesh.java
  engine/src/main/java/org/terasology/engine/world/block/shapes/BlockMeshPart.java
Labels: Type: Improvement

#4913 test(modules): make com.google.truth assertion library available
  build-logic/src/main/kotlin/terasology-module.gradle.kts
  engine-tests/build.gradle
  engine/build.gradle
Labels: Category: Test/QA, Size: S, Type: Chore

#4903 chore: update vertex attribute with put(T[] data)
  engine-tests/src/test/java/org/terasology/engine/rendering/assets/mesh/VertexAttributeBindingTest.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexAttributeBinding.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexFloatAttributeBinding.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/resource/VertexIntegerAttributeBinding.java
Labels: Type: Chore

#4902 feat(RelevanceSystem): addRelevanceEntity returns the relevant region
  engine/src/main/java/org/terasology/engine/world/chunks/localChunkProvider/LocalChunkProvider.java
  engine/src/main/java/org/terasology/engine/world/chunks/localChunkProvider/RelevanceSystem.java
  engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
Labels: Type: Improvement, Category: Test/QA, Size: S

#4907 fix(headless-fixes): remove InputSystem and NuiManager from headlesses
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/core/modes/AbstractState.java
  engine/src/main/java/org/terasology/engine/core/modes/StateIngame.java
  engine/src/main/java/org/terasology/engine/core/modes/StateLoading.java
  engine/src/main/java/org/terasology/engine/core/modes/StateMainMenu.java
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/HeadlessInput.java
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/mode/StateHeadlessSetup.java
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/renderer/HeadlessWorldRenderer.java
  engine/src/main/java/org/terasology/engine/input/InputSystem.java
  engine/src/main/java/org/terasology/engine/logic/chat/ChatSystem.java
  engine/src/main/java/org/terasology/engine/logic/console/ConsoleSystem.java
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Type: Bug, Status: Needs Testing
