Repository MovingBlocks/Terasology, pull requests merged in 2022-11, with the labels that each got.

#5070 ci: add workflow to auto-add issues and PRs to projects
  .github/workflows/project-autoadd.yml
Labels: Category: Build/CI, Status: Needs Discussion, Type: Improvement, Size: S

#5071 ci: add workflow autoclosing issues with unresponsive authors
  .github/workflows/autoclose.yml
Labels: Category: Build/CI, Type: Improvement

#5080 ci: fix project-autoadd github action
  .github/workflows/project-autoadd.yml
Labels: Type: Bug, Category: Build/CI, Topic: Stabilization

#5079 doc: document restrictions for BindButtonEvent
  engine/src/main/java/org/terasology/engine/input/BindButtonEvent.java
Labels: Category: Doc, Type: Improvement, Topic: Stabilization, Size: S
