Repository MovingBlocks/Terasology, pull requests merged in 2022-08, with the labels that each got.

#5065 build(idea): fix parameters in run configurations
  .idea/runConfigurations/TerasologyPC__2nd_client_for_mac.xml
  .idea/runConfigurations/TerasologyPC_for_mac.xml
Labels: Type: Bug, Category: Build/CI, Size: S

#5064 chore: simplify implementation in Assets to one-liners
  engine/src/main/java/org/terasology/engine/utilities/Assets.java
Labels: Size: S, Type: Chore

#5068 build(idea): exclude some things from import suggestions
  .idea/codeInsightSettings.xml
  .idea/kotlinc.xml
Labels: Category: Build/CI

#5066 fix(rendering): Don't try to set window icon on macOS
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglGraphics.java
Labels: Type: Bug, Topic: Rendering, Topic: Stabilization, Size: S

#5067 chore(world): improve logging for BlockManager
  engine/src/main/java/org/terasology/engine/world/block/internal/BlockManagerImpl.java
Labels: Topic: Stabilization, Size: S, Type: Chore

#5062 fix: do not crash on unexpected map format in GenericMapTypeHandler
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandler.java
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandlerTest.java
Labels: Type: Bug, Category: Build/CI, Status: Needs Discussion, Status: Needs Testing, Size: S, Category: Crash

#5061 feat: add type handlers for SimpleUri and BlockUri
  engine-tests/src/test/java/org/terasology/engine/persistence/typeHandling/extensionTypes/BlockUriTypeHandlerTest.java
  engine-tests/src/test/java/org/terasology/engine/persistence/typeHandling/extensionTypes/SimpleUriTypeHandlerTest.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/TypeHandlerLibraryImpl.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/BlockUriTypeHandler.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/SimpleUriTypeHandler.java
Labels: Type: Improvement, Size: S

#5063 chore(subsystems/discord): catch runtime exception and log only message
  subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCThread.java
Labels: Type: Bug, Topic: Stabilization, Size: S, Type: Chore
