Repository MovingBlocks/Terasology, pull requests merged in 2022-01, with the labels that each got.

#4984 chore: add security policy
  .github/SECURITY.md
Labels: Category: Doc, Category: Security, Size: S, Type: Chore

#4972 refactor: split out chunk work as a seperate helper class
  engine/src/main/java/org/terasology/engine/rendering/world/ChunkMeshWorker.java
  engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java
  engine/src/main/java/org/terasology/engine/world/chunks/LodChunkProvider.java
Labels: Type: Refactoring

#4989 refactor(Chunk): provide default implementations of methods where possible
  engine/src/main/java/org/terasology/engine/world/chunks/Chunk.java
  engine/src/main/java/org/terasology/engine/world/chunks/internal/ChunkImpl.java
  engine/src/main/java/org/terasology/engine/world/chunks/internal/PreLodChunk.java
Labels: Size: S, Topic: WorldGen, Type: Refactoring

#4992 chore: remove no longer existing CharacterMovement fields from prefabs
  engine/src/main/resources/org/terasology/engine/assets/prefabs/player/player.prefab
Labels: Topic: Stabilization, Size: S, Type: Chore
