Repository MovingBlocks/Terasology, pull requests merged in 2022-05, with the labels that each got.

#5006 fix: path quirk on an M1 Mac using Azul JDK 11
  build-logic/src/main/kotlin/org/terasology/gradology/file_operations.kt
  build.gradle
Labels: Type: Bug, Category: Build/CI

#5007 build(idea): update dictionary and gitignores
  .idea/.gitignore
  .idea/dictionaries/kevint.xml
  .idea/misc.xml
Labels: Category: Build/CI, Size: S, Type: Chore

#4987 test(ChunkMeshWorker): initial attempt at using reactor-test
  engine-tests/build.gradle
  engine-tests/src/test/java/org/terasology/engine/rendering/world/ChunkMeshWorkerTest.java
  engine-tests/src/test/java/org/terasology/engine/rendering/world/DummyChunk.java
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/rendering/logic/ChunkMeshComponent.java
  engine/src/main/java/org/terasology/engine/rendering/logic/EntityBasedRenderableChunk.java
  engine/src/main/java/org/terasology/engine/rendering/world/ChunkMeshWorker.java
  engine/src/main/java/org/terasology/engine/world/chunks/LodChunk.java
  engine/src/main/java/org/terasology/engine/world/chunks/internal/ChunkImpl.java
Labels: Category: Test/QA, Topic: Concurrency

#5008 fix(SelectionScreen): be more robust in the face of save files with incomplete manifests
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseWorld.java
  engine/src/main/java/org/terasology/engine/game/GameManifest.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectionScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/savedGames/GameInfo.java
Labels: Type: Bug

#4786 chore(rendering): migrate chunk mesh generation Flux
  engine-tests/build.gradle
  engine-tests/src/test/java/org/terasology/engine/rendering/world/ChunkMeshWorkerTest.java
  engine-tests/src/test/java/org/terasology/engine/rendering/world/DummyChunk.java
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/rendering/logic/ChunkMeshComponent.java
  engine/src/main/java/org/terasology/engine/rendering/logic/EntityBasedRenderableChunk.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkMesh.java
  engine/src/main/java/org/terasology/engine/rendering/primitives/ChunkTessellator.java
  engine/src/main/java/org/terasology/engine/rendering/world/ChunkMeshUpdateManager.java
  engine/src/main/java/org/terasology/engine/rendering/world/ChunkMeshWorker.java
  engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorld.java
  engine/src/main/java/org/terasology/engine/rendering/world/RenderableWorldImpl.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java
  engine/src/main/java/org/terasology/engine/world/chunks/Chunk.java
  engine/src/main/java/org/terasology/engine/world/chunks/LodChunk.java
  engine/src/main/java/org/terasology/engine/world/chunks/LodChunkProvider.java
  engine/src/main/java/org/terasology/engine/world/chunks/internal/ChunkImpl.java
  engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkTask.java
  engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ShutdownChunkTask.java
Labels: Type: Chore, Topic: Concurrency

#5009 chore(StorageManager): typos and minor code cleanups
  engine-tests/src/test/java/org/terasology/engine/persistence/internal/StorageManagerTest.java
  engine/src/main/java/org/terasology/engine/persistence/internal/ReadWriteStorageManager.java
  engine/src/main/java/org/terasology/engine/persistence/internal/SaveTransaction.java
  engine/src/main/java/org/terasology/engine/world/generator/WorldConfigurator.java
Labels: Size: S, Type: Chore

#5014 fix(ChunkProcessingPipeline): base thread pool size on available processors
  engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
Labels: Type: Bug, Category: Performance, Blocker, Size: S

#5013 fix(test): set jacoco excludes for engine-test's unitTest and integrationTest tasks
  config/gradle/common.gradle
  engine-tests/build.gradle
Labels: Type: Bug, Category: Test/QA, Size: S

#5016 chore: remove unused ByteCodeReflectFactory
  engine-tests/src/test/java/org/terasology/reflection/reflect/ByteCodeReflectFactoryTest.java
  engine/build.gradle
  engine/src/jmh/java/org/terasology/benchmark/reflectFactory/ReflectionFactoryBenchmark.java
  engine/src/main/java/org/terasology/engine/reflection/package-info.java
  engine/src/main/java/org/terasology/engine/reflection/reflect/ByteCodeReflectFactory.java
Labels: Size: S, Type: Chore

#5020 build: extract project metrics/analytics to terasology-metrics gradle plugin
  Jenkinsfile
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/facade.gradle.kts
  build-logic/src/main/kotlin/terasology-common.gradle.kts
  build-logic/src/main/kotlin/terasology-metrics.gradle.kts
  build-logic/src/main/kotlin/terasology-module.gradle.kts
  build.gradle
  config/gradle/common.gradle
  engine-tests/build.gradle
  engine/build.gradle
  facades/PC/build.gradle.kts
  subsystems/DiscordRPC/build.gradle.kts
  subsystems/TypeHandlerLibrary/build.gradle.kts
  templates/build.gradle
Labels: Category: Build/CI

#5019 doc: replace IRC link with Discord
  .github/CONTRIBUTING.md
Labels: Category: Doc, Size: S

#5017 fix(Context)!: correct signature of Context.get
  engine-tests/src/test/java/org/terasology/engine/registry/CoreRegistryTest.java
  engine/src/main/java/org/terasology/engine/context/Context.java
  engine/src/main/java/org/terasology/engine/context/internal/ContextImpl.java
  engine/src/main/java/org/terasology/engine/context/internal/MockContext.java
Labels: Type: Bug, Size: S

#5010 test: Move ModuleTestingEnvironment to engine-tests
  build-logic/src/main/kotlin/terasology-module.gradle.kts
  engine-tests/build.gradle
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/ChunkRegionFuture.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/Engines.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/MainLoop.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/ModuleTestingEnvironment.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/ModuleTestingHelper.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/Scopes.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/TestEventReceiver.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/TestingStateHeadlessSetup.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/fixtures/BaseTestingClass.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/jupiter/Dependencies.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/jupiter/IsolatedMTEExtension.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/jupiter/MTEExtension.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/jupiter/UseWorldGenerator.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/package-info.java
  engine-tests/src/main/java/org/terasology/unittest/stubs/DummyComponent.java
  engine-tests/src/main/java/org/terasology/unittest/stubs/DummyEvent.java
  engine-tests/src/main/java/org/terasology/unittest/stubs/DummySystem.java
  engine-tests/src/main/java/org/terasology/unittest/worlds/DummyWorldGenerator.java
  engine-tests/src/main/java/org/terasology/unittest/worlds/EmptyWorldGenerator.java
  engine-tests/src/main/java/org/terasology/unittest/worlds/FlatSurfaceHeightProvider.java
  engine-tests/src/main/java/org/terasology/unittest/worlds/StubWorldGenerator.java
  engine-tests/src/main/java/org/terasology/unittest/worlds/package-info.java
  engine-tests/src/main/resources/org/terasology/engine/integrationenvironment/jupiter/default-logback.xml
  engine-tests/src/main/resources/org/terasology/unittest/assets/behaviors/BehaviorEmptyLookup.behavior
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/AssetLoadingTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ChunkRegionFutureTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ClientConnectionTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ComponentSystemTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ExampleTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/IsolatedEngineTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/MTEExtensionTestWithPerClassLifecycle.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/MTEExtensionTestWithPerMethodLifecycle.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ModuleTestingEnvironmentTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/NestedTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/SubclassInjectionTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/TestEventReceiverTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/WorldProviderTest.java
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/delay/DelayManagerTest.java
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleManager.java
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/mode/StateHeadlessSetup.java
  engine/src/main/java/org/terasology/engine/logic/chat/ChatSystem.java
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayer.java
  engine/src/main/java/org/terasology/engine/network/internal/ServerHandshakeHandler.java
  engine/src/main/java/org/terasology/engine/world/generator/internal/WorldGeneratorManager.java
Labels: Size: M, Category: Test/QA

#4621 feat: Add BlockAreac#distanceSquared
  engine-tests/src/test/java/org/terasology/engine/world/block/BlockAreaTest.java
  engine/src/main/java/org/terasology/engine/world/block/BlockArea.java
  engine/src/main/java/org/terasology/engine/world/block/BlockAreac.java
Labels: Type: Improvement

#5021 security: upgrade dependencies
  build-logic/build.gradle.kts
  engine-tests/build.gradle
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/config/flexible/constraints/StringConstraint.java
  engine/src/main/java/org/terasology/engine/telemetry/TelemetryEmitter.java
  facades/PC/build.gradle.kts
  subsystems/DiscordRPC/build.gradle.kts
Labels: Category: Security, Size: S, Type: Chore

#5026 chore(#4908): match IntelliJ and Checkstyle formatting rules
  .idea/codeStyles/Project.xml
Labels: Category: Build/CI, Size: S, Type: Chore

#5025 feat(#4948): restrict default memory settings
  build-logic/src/main/kotlin/org/terasology/gradology/exec.kt
Labels: Type: Improvement
