Repository MovingBlocks/Terasology, pull requests merged in 2023-07, with the labels that each got.

#5112 refactor: remove vr support
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/Engines.java
  engine/src/main/java/org/terasology/engine/config/RenderingConfig.java
  engine/src/main/java/org/terasology/engine/core/modes/StateIngame.java
  engine/src/main/java/org/terasology/engine/core/subsystem/openvr/OpenVRControllers.java
  engine/src/main/java/org/terasology/engine/core/subsystem/openvr/OpenVRInput.java
  engine/src/main/java/org/terasology/engine/logic/players/FirstPersonHeldItemMountPointComponent.java
  engine/src/main/java/org/terasology/engine/logic/players/LocalPlayerSystem.java
  engine/src/main/java/org/terasology/engine/rendering/cameras/OpenVRStereoCamera.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java
  engine/src/main/java/org/terasology/engine/rendering/openvrprovider/ControllerListener.java
  engine/src/main/java/org/terasology/engine/rendering/openvrprovider/OpenVRProvider.java
  engine/src/main/java/org/terasology/engine/rendering/openvrprovider/OpenVRState.java
  engine/src/main/java/org/terasology/engine/rendering/openvrprovider/OpenVRUtil.java
  engine/src/main/java/org/terasology/engine/rendering/openvrprovider/package-info.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/videoMenuScreen.ui
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Status: Needs Discussion, Topic: Rendering, Size: S, Type: Refactoring

#5115 refactor!: remove TeraEd facade
  .gitignore
  .idea/runConfigurations/TeraEd__rendering_editor_.xml
  config/groovy/facade.groovy
  facades/TeraEd/.gitignore
  facades/TeraEd/build.gradle
  facades/TeraEd/src/main/java/org/terasology/editor/TeraEd.java
  facades/TeraEd/src/main/java/org/terasology/editor/input/AwtKeyboardDevice.java
  facades/TeraEd/src/main/java/org/terasology/editor/input/AwtMouseDevice.java
  facades/TeraEd/src/main/java/org/terasology/editor/properties/FloatProperty.java
  facades/TeraEd/src/main/java/org/terasology/editor/properties/Property.java
  facades/TeraEd/src/main/java/org/terasology/editor/properties/PropertyProvider.java
  facades/TeraEd/src/main/java/org/terasology/editor/properties/ReflectionProvider.java
  facades/TeraEd/src/main/java/org/terasology/editor/properties/SceneProperties.java
  facades/TeraEd/src/main/java/org/terasology/editor/subsystem/AwtInput.java
  facades/TeraEd/src/main/java/org/terasology/editor/subsystem/LwjglPortlet.java
  facades/TeraEd/src/main/java/org/terasology/editor/subsystem/LwjglPortletDisplayDevice.java
  facades/TeraEd/src/main/java/org/terasology/editor/ui/MainWindow.java
  facades/TeraEd/src/main/java/org/terasology/editor/ui/PropertyPanel.java
  facades/TeraEd/src/main/java/org/terasology/editor/ui/PropertySlider.java
  facades/TeraEd/src/main/java/org/terasology/editor/ui/Viewport.java
  facades/TeraEd/src/main/resources/logback.xml
Labels: Topic: Stabilization, Breaking Change, Type: Refactoring

#5119 ci: configure jenkins to abort builds if new builds are triggered
  Jenkinsfile
Labels: Category: Build/CI, Type: Improvement, Status: Needs Testing, Size: S

#5106 feat(netork)!: rewrite ping logic
  engine/src/main/java/org/terasology/engine/network/PingComponent.java
  engine/src/main/java/org/terasology/engine/network/PingStockComponent.java
  engine/src/main/java/org/terasology/engine/network/PingSubscriberComponent.java
  engine/src/main/java/org/terasology/engine/network/ServerPingSystem.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/ingame/OnlinePlayersOverlay.java
  engine/src/main/resources/org/terasology/engine/assets/ui/onlinePlayersOverlay.ui
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandler.java
Labels: Multiplayer, Type: Improvement

#5117 test(TypeHandler): More tests for empty collections
  engine-tests/src/main/resources/org/terasology/unittest/assets/prefabs/withEmptyListContainer.prefab
  engine-tests/src/test/java/org/terasology/engine/entitySystem/PrefabTest.java
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/ArrayTypeHandlerTest.java
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/CollectionTypeHandlerTest.java
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandlerTest.java
Labels: Topic: Stabilization, Category: Test/QA, Size: S, Type: Chore

#5116 refactor!: remove multi-world support
  .idea/kotlinc.xml
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/PreviewWorldScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/StartPlayingScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/UniverseSetupScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/WorldSetupScreen.java
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_cs.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_de.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_en.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_fr.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_ja.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_sq.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_uk.lang
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/previewWorldScreen.ui
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/universeSetupScreen.ui
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/worldPreGenerationScreen.ui
  engine/src/main/resources/org/terasology/engine/assets/ui/worldSetupScreen.ui
Labels: Topic: UI/UX, Type: Refactoring

#5118 refactor: merge spawn preview screen into world pre generation screen
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/StartPlayingScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/startPlayingScreen.ui
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/worldPreGenerationScreen.ui
Labels: Topic: UI/UX, Type: Refactoring

#5123 doc(facade/PC): add README
  facades/PC/README.md
  facades/PC/docs/pc-facade-overview.drawio.svg
Labels: Category: Doc
