Repository MovingBlocks/Terasology, pull requests merged in 2023-11, with the labels that each got.

#5160 perf(rendering): use MONO rendering stage
  engine/src/main/java/org/terasology/engine/core/modes/StateIngame.java
Labels: Category: Performance, Topic: Rendering

#5165 chore: init metrics only if monitoring enabled
  engine-tests/src/test/java/org/terasology/engine/integrationenvironment/ExampleTest.java
  engine/src/main/java/org/terasology/engine/core/subsystem/common/MonitoringSubsystem.java
Labels: Type: Improvement, Topic: Stabilization, Size: S, Type: Chore

#5163 fix: move readme images back into docs folder
  docs/images/PopulatedVillage.jpg
  docs/images/discord.png
  docs/images/facebook.png
  docs/images/forum.png
  docs/images/menuBackground.jpg
  docs/images/patreon.jpg
  docs/images/reddit.png
  docs/images/terasology-logo.png
  docs/images/twitter.png
  docs/images/youtube.png
Labels: Type: Bug, Category: Doc

#5164 doc: add link to docsified engine wiki
  README.md
Labels: Category: Doc, Topic: UI/UX, Type: Improvement, Size: S

#5170 logger qa, use parameterized logger.
  engine/src/main/java/org/terasology/engine/config/flexible/AutoConfigTypeHandler.java
  engine/src/main/java/org/terasology/engine/config/flexible/internal/SettingImpl.java
  engine/src/main/java/org/terasology/engine/core/ComponentSystemManager.java
  engine/src/main/java/org/terasology/engine/core/module/SandboxFileManager.java
  engine/src/main/java/org/terasology/engine/logic/behavior/actions/conditions/ConditionAction.java
  engine/src/main/java/org/terasology/engine/rendering/dag/AbstractNode.java
  engine/src/main/java/org/terasology/engine/rendering/dag/RenderGraph.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/AbstractFboManager.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLShader.java
  engine/src/main/java/org/terasology/engine/world/chunks/blockdata/ExtraBlockDataManager.java
  engine/src/main/java/org/terasology/engine/world/generator/internal/WorldGeneratorManager.java
Labels: Topic: Stabilization, Type: Refactoring

#5168 test: split and improve ObjectFieldMapTypeHandlerFactoryTests
  subsystems/TypeHandlerLibrary/src/test/java/org/terasology/persistence/typeHandling/coreTypes/factories/ObjectFieldMapTypeHandlerFactoryTest.java
Labels: Type: Improvement, Topic: Stabilization, Category: Test/QA

#5122 refactor: merge universe setup into world pregen screen
  engine/src/main/java/org/terasology/engine/core/subsystem/headless/mode/StateHeadlessSetup.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/GameManifestProvider.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/NewGameScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/UniverseSetupScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/UniverseWrapper.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/WorldPreGenerationScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/WorldSetupScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldSetupWrapper.java
  engine/src/main/java/org/terasology/engine/world/internal/WorldInfo.java
  engine/src/main/java/org/terasology/engine/world/internal/WorldProviderCoreImpl.java
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/universeSetupScreen.ui
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/worldPreGenerationScreen.ui
  engine/src/main/resources/org/terasology/engine/assets/ui/worldSetupScreen.ui
Labels: Topic: UI/UX, Type: Refactoring

#5175 refactor: remove unused local var for artifactview
  build-logic/src/main/kotlin/org/terasology/gradology/module_deps.kt
Labels: Topic: Stabilization, Category: Test/QA, Size: S, Type: Refactoring

#5172 doc: fix broken links
  .github/CODE_OF_CONDUCT.md
  README.md
  docs/Modules.md
  docs/Playing.md
Labels: Type: Bug, Category: Doc, Topic: Stabilization, Size: S

#5173 qa: parametrize logger usages
  build-logic/src/main/kotlin/terasology-metrics.gradle.kts
  build-logic/src/main/kotlin/terasology-module.gradle.kts
  engine-tests/build.gradle
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/Engines.java
  engine-tests/src/main/java/org/terasology/engine/integrationenvironment/IntegrationEnvironmentSubsystem.java
  engine/build.gradle
  engine/src/main/java/org/terasology/engine/config/RenderingDebugConfig.java
  engine/src/main/java/org/terasology/engine/core/TerasologyEngine.java
  engine/src/main/java/org/terasology/engine/core/modes/StateLoading.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleListDownloader.java
  engine/src/main/java/org/terasology/engine/entitySystem/event/internal/EventSystemImpl.java
  engine/src/main/java/org/terasology/engine/i18n/TranslationSystemImpl.java
  engine/src/main/java/org/terasology/engine/logic/behavior/core/ActionNode.java
  engine/src/main/java/org/terasology/engine/logic/characters/CharacterSystem.java
  engine/src/main/java/org/terasology/engine/logic/config/ModuleConfigSystem.java
  engine/src/main/java/org/terasology/engine/logic/inventory/ItemPickupAuthoritySystem.java
  engine/src/main/java/org/terasology/engine/network/internal/ClientConnectionHandler.java
  engine/src/main/java/org/terasology/engine/network/internal/NetworkSystemImpl.java
  engine/src/main/java/org/terasology/engine/network/internal/ServerInfoRequestHandler.java
  engine/src/main/java/org/terasology/engine/persistence/internal/GlobalStoreLoader.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/TextureRegionAssetTypeHandler.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/TextureRegionTypeHandler.java
  engine/src/main/java/org/terasology/engine/persistence/typeHandling/extensionTypes/UITextureRegionTypeHandler.java
  engine/src/main/java/org/terasology/engine/recording/EventCopier.java
  engine/src/main/java/org/terasology/engine/recording/EventSystemReplayImpl.java
  engine/src/main/java/org/terasology/engine/rendering/assets/atlas/AtlasFormat.java
  engine/src/main/java/org/terasology/engine/rendering/dag/AbstractNode.java
  engine/src/main/java/org/terasology/engine/rendering/dag/ModuleRendering.java
  engine/src/main/java/org/terasology/engine/rendering/dag/RenderGraph.java
  engine/src/main/java/org/terasology/engine/rendering/dag/RenderTaskListGenerator.java
  engine/src/main/java/org/terasology/engine/rendering/nui/asset/UIDeltaFormat.java
  engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/NUIEditorScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/editor/layers/NUISkinEditorScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/editor/utils/NUIEditorMenuTreeBuilder.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/SelectionScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/advancedGameSetupScreen/AdvancedGameSetupScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/savedGames/GameProvider.java
  engine/src/main/java/org/terasology/engine/rendering/nui/widgets/UIButtonWebBrowser.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/AbstractFboManager.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/GLSLShader.java
  engine/src/main/java/org/terasology/engine/rendering/world/WorldRendererImpl.java
  engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
  engine/src/main/resources/org/terasology/engine/logback/setup.xml
  facades/PC/build.gradle.kts
  subsystems/DiscordRPC/src/main/java/org/terasology/subsystem/discordrpc/DiscordRPCThread.java
  subsystems/TypeHandlerLibrary/src/main/java/org/terasology/persistence/typeHandling/coreTypes/GenericMapTypeHandler.java
Labels: Type: Improvement, Topic: Stabilization, Category: Test/QA

#5184 doc: Contributor Quick Start JDK 17
  docs/Contributor-Quick-Start.md
Labels: Category: Doc, Topic: UI/UX, Type: Improvement, Size: S
