Repository MovingBlocks/Terasology, pull requests merged in 2024-04, with the labels that each got.

#5233 feat: make WorldConfigurator subscribable
  engine/src/main/java/org/terasology/engine/world/generation/FacetedWorldConfigurator.java
  engine/src/main/java/org/terasology/engine/world/generator/WorldConfigurator.java
  engine/src/main/java/org/terasology/engine/world/generator/WorldConfiguratorAdapter.java
Labels: Topic: Architecture, Type: Improvement, Size: S

#5225 chore: update JNBullet to 1.0.4
  build.gradle.kts
  engine/build.gradle
Labels: Type: Chore

#5226 refactor: merge world config in setup screen
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/UniverseSetupScreen.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/WorldSetupScreen.java
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/universeSetupScreen.ui
  engine/src/main/resources/org/terasology/engine/assets/ui/worldSetupScreen.ui
Labels: Topic: UI/UX, Size: M, Status: Needs Testing, Type: Refactoring

#5238 feat: throttle chunk processing based on deadline
  engine/src/main/java/org/terasology/engine/world/chunks/localChunkProvider/LocalChunkProvider.java
Labels: Type: Improvement

#5237 feat: make number of chunk processing threads configurable
  engine-tests/src/test/java/org/terasology/engine/world/chunks/localChunkProvider/LocalChunkProviderTest.java
  engine-tests/src/test/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipelineTest.java
  engine/src/main/java/org/terasology/engine/config/RenderingConfig.java
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseRemoteWorld.java
  engine/src/main/java/org/terasology/engine/core/modes/loadProcesses/InitialiseWorld.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java
  engine/src/main/java/org/terasology/engine/world/chunks/localChunkProvider/LocalChunkProvider.java
  engine/src/main/java/org/terasology/engine/world/chunks/pipeline/ChunkProcessingPipeline.java
  engine/src/main/java/org/terasology/engine/world/chunks/remoteChunkProvider/RemoteChunkProvider.java
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu.lang
  engine/src/main/resources/org/terasology/engine/assets/i18n/menu_en.lang
  engine/src/main/resources/org/terasology/engine/assets/ui/menu/videoMenuScreen.ui
Labels: Type: Improvement
