Repository MovingBlocks/Terasology, pull requests merged in 2024-10, with the labels that each got.

#5274 qa: address pmd findings
  engine/src/main/java/org/terasology/engine/core/LoggingContext.java
  engine/src/main/java/org/terasology/engine/core/PathManager.java
  engine/src/main/java/org/terasology/engine/core/module/ModuleInstaller.java
  engine/src/main/java/org/terasology/engine/core/module/rendering/RenderingModuleRegistry.java
  engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/DebugCallback.java
  engine/src/main/java/org/terasology/engine/entitySystem/entity/lifecycleEvents/BeforeEntityCreated.java
  engine/src/main/java/org/terasology/engine/logic/behavior/asset/GroupBuilder.java
  engine/src/main/java/org/terasology/engine/logic/debug/MovementDebugCommands.java
  engine/src/main/java/org/terasology/engine/logic/spawner/AbstractSpawner.java
  engine/src/main/java/org/terasology/engine/network/internal/ServerConnectListManager.java
  engine/src/main/java/org/terasology/engine/persistence/serializers/PrefabSerializer.java
  engine/src/main/java/org/terasology/engine/physics/bullet/shapes/BulletConvexHullShape.java
  engine/src/main/java/org/terasology/engine/rendering/assets/mesh/ObjMeshFormat.java
  engine/src/main/java/org/terasology/engine/rendering/assets/skeletalmesh/SkeletalMeshData.java
  engine/src/main/java/org/terasology/engine/rendering/assets/texture/AWTTextureFormat.java
  engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/UniverseSetupScreen.java
  engine/src/main/java/org/terasology/engine/rendering/opengl/OpenGLMeshBase.java
  engine/src/main/java/org/terasology/engine/world/time/WorldTimeImpl.java
  facades/PC/src/main/java/org/terasology/engine/Terasology.java
Labels: Size: M, Topic: Stabilization, Status: Needs Testing, Category: Test/QA, Type: Refactoring

#5283 gradle versions catalog, not yet for build-logic
  engine-tests/build.gradle.kts
  engine/build.gradle.kts
  facades/PC/build.gradle.kts
  settings.gradle.kts
  subsystems/DiscordRPC/build.gradle.kts
  subsystems/TypeHandlerLibrary/build.gradle.kts
Labels: Category: Build/CI

#5288 fix: switch typo in ConditionAction
  engine/src/main/java/org/terasology/engine/logic/behavior/actions/conditions/ConditionAction.java
Labels: Type: Bug, Category: Gameplay Content, Topic: AI, Size: S
